### ISSUE TITLE
Newtonsoft Parsing Error on MailFolderMessagesCollectionRequest.GetAsync

### ISSUE THREAD

**Issue by amartinrelativity** [microsoftgraph/msgraph-sdk-dotnet#1048]
While paging through mail messages in a folder using `MailFolderMessagesCollectionRequest.GetAsync`, we are randomly getting Newtonsoft parsing exceptions. It appears to be transient as retrying a similar query later doesn't trigger the issue.

We are using the following versions:

- Microsoft.Graph - 3.27.0
- Microsoft.Graph.Core - 1.24.0 

`Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: r. Path 'value[14].body.content', line 1, position 64521.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Graph.DerivedTypeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Converters.CustomCreationConverter1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Graph.Serializer.DeserializeObject[T](String inputString)
   at Microsoft.Graph.ResponseHandler.HandleResponse[T](HttpResponseMessage response)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.MailFolderMessagesCollectionRequest.GetAsync(CancellationToken cancellationToken)`

 
[AB#10028](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10028)

**Comment by andrueastman** [comment]
Hey @amartinrelativity,

Thanks for raising this issue with us. 
It would be very helpful if we could get like a sample of the response string from the request so that we could identify what in the payload is causing the exception. You could check out [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/docs/logging-requests.md)on how to log requests.

**Comment by amartinrelativity** [comment]
Thanks @andrueastman - this is from a client environment, so I will have to see if it is feasible for us to pull the response out for logging purposes. Are there any other options available outside of that for diagnosing this?

**Comment by andrueastman** [comment]
> Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: r. Path 'value[14].body.content

@amartinrelativity From the stack trace you provided, it looks like the serializer does not like a character in the response payload. Unless we know the character, it'll be quite difficult to mitigate the issue. 

Another alternative is to try out the [preview version](https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.7) of the next major version that uses System.Text.Json and drops NewtonSoft and see if you run into similar issue. 
You can check out the upgrade guide [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/2.0/docs/upgrade-to-v4.md).

**Comment by amartinrelativity** [comment]
Okay thanks, we're working on adding additional logging to find what the offending character is. I'm hoping to have an update towards end of week.
