### ISSUE TITLE
Deleting attachments and creating e-mail properties can cause the exception ErrorIrresolvableConflict

### ISSUE THREAD

**Issue by maffer1** [microsoftgraph/msgraph-sdk-dotnet#1195]
**Describe the bug**
We have a C# application that saves emails and their attachments into our DMS system from Office/Outlook 365 accounts. We use the Microsoft Graph REST API to do this. After saving a copy of the original email in the DMS system, we delete the attachments from the original email and set some properties on it.
When deleting attachments or creating email properties with Microsoft Graph, the following exception can occur: 
**Status Code: PreconditionFailed Microsoft.Graph.ServiceException: Code: ErrorIrresolvableConflict** ... 

**To Reproduce**

Copy an email with several attachments about 100 times in a folder of an Outlook account, then loop through all emails and delete the attachments and create the properties. In most cases, this will be successful, but in some cases, the exception ErrorIrresolvableConflict will be thrown.
I have written a test application "KendoxMailArchiver_MicrosoftGraph_Test.zip" to reproduce the problem. The test application is registered in Azure AD with the following application permissions: Mail.ReadWrite, User.Read.All

[How to reproduce the problem.docx](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/7702102/How.to.reproduce.the.problem.docx)

Test application:
[KendoxMailArchiver_MicrosoftGraph_Test.zip] (https://kendox-my.sharepoint.com/:u:/p/paul_mafli/Eecixtk2mR1LoiCm4d4TWrgBzs4c1FXCLeXNOTb0Tp2nVQ?e=dWvaqb)

[Register application in Azure AD.pdf](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/7702239/Register.application.in.Azure.AD.pdf)

Error:

Microsoft.Graph.ServiceException: Code: ErrorIrresolvableConflict
Message: The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item.
ClientRequestId: 2e77c4f3-bbbc-4321-885b-7fc923fdf067

   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__40.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.MessageRequest.<UpdateAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Com.Kendox.MailArchiver.Library.MailProviders.MicrosoftGraph.MicrosoftGraphItem.<UpdateMessageAsync>d__150.MoveNext() in C:\Develop\Kendox MailArchiver\Dev\Kendox MailArchiver Library\MailProviders\MicrosoftGraph\MicrosoftGraphItem.cs:line 1353
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Com.Kendox.MailArchiver.Library.MailProviders.MicrosoftGraph.MicrosoftGraphItem.UpdateItem() in C:\Develop\Kendox MailArchiver\Dev\Kendox MailArchiver Library\MailProviders\MicrosoftGraph\MicrosoftGraphItem.cs:line 606
   at Com.Kendox.MailArchiver.MailBox.MailBoxArchiving.SaveItem(IItem item, String temporaryExportFilePath) in C:\Develop\Kendox MailArchiver\Dev\Kendox MailArchiver EWS Clean\MailBoxArchiving.cs:line 504

**Expected behavior**
The exception ErrorIrresolvableConflict will not be thrown in the above scenario.  

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise

**Additional context**

**Comment by MIchaelMainer** [comment]
Do you have any cases that make any changes to the original email before deleting the attachment? This could cause this conflict.

**Comment by maffer1** [comment]
No. The attachments are removed from the original email. The exception ErrorIrresolvableConflict is thrown when you work with copies of the original email.

I have also a similar issue open:  [Add](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1201)
This issue is now labeled as service issue. Maybe something will happen there.
