### ISSUE TITLE
Upgrading to 4.12.0 from 4.11.0 server starts throwing `TargetInvocationException`

### ISSUE THREAD

**Issue by CraigSelbert** [microsoftgraph/msgraph-sdk-dotnet#1207]
**Describe the bug**
After Upgrading to 4.12.0 from 4.11.0 server starts throwing `TargetInvocationException`

**To Reproduce**
1. Updated NuGet Package from 4.11.0 to 4.12.0
2. Run web application
3. System throws following exception

    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Derived method 'GetBaseConfigurationAsync' in type 'Microsoft.IdentityModel.Protocols.ConfigurationManager`1' from assembly 'Microsoft.IdentityModel.Protocols, Version=6.14.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' cannot reduce access.
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerOptions..ctor()
   at System.RuntimeType.CreateInstanceOfT()
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at Microsoft.Extensions.Options.OptionsFactory`1.CreateInstance(String name)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)
   at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)
   at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Swank.Web.Server.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext httpContext) in E:\Stash\ss\scorpion\Api\Middleware\CacheHeaderMiddleware.cs:line 40
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Swank.Web.Server.Middleware.ExecutionPerformanceMiddleware.Invoke(HttpContext httpContext)
   at Swank.Web.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext httpContext)

**Expected behavior**
Web application to behave normally, allow Azure AD authentication

**Desktop (please complete the following information):**
 - OS: Windows
 - Dotnet 6.0 (6.0.101)

**Additional context**
We have been using Azure AD for our web application for a while. Not sure what is going on here

**Comment by andrueastman** [comment]
Hey @CraigSelbert,

Thanks for raising this. 

The 4.12.0 release only had a related change that involved bumping Microsoft.IdentityModel.Protocols to version 6.14.1. Any chance you are still able to replicate this with the latest 4.13.0 version that bumps Microsoft.IdentityModel.Protocols to the latest version 6.15.0?

If not, are you able to share the contents of your csproj to help us understand the issue better?

**Comment by CraigSelbert** [comment]
After upgrading to `4.13.0` the problem has been resolved. Thanks for the update and help.
