### ISSUE TITLE
graphServiceClient.Me.SendMail.PostAsync(requestBody)

### ISSUE THREAD

**Issue by Dale-Dr** [microsoftgraph/msgraph-sdk-dotnet#1681]
**Describe the bug**
When attempting to send an email with the Microsoft.Graph.Me.SendMail method I'm getting the following error:

DemoGraph.Controllers.HomeController: Error: Error: Microsoft.Graph.Models.ODataErrors.ODataError: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendNoContentAsync(RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendNoContentAsync(RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.SendMail.SendMailRequestBuilder.PostAsync(SendMailPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
   at DemoGraph.Graph.GraphServices.SendEmailMessage(String nameSendTo, GraphServiceClient graphServiceClient, String subject, String emailBody, ILogger log) in C:\Users\dadrape_adm\source\repos\DemoGraph\DemoGraph\Graph\GraphServices.cs:line 48
   at DemoGraph.Controllers.HomeController.SendMail() in C:\Users\dadrape_adm\source\repos\DemoGraph\DemoGraph\Controllers\HomeController.cs:line 77

But when using the Microsoft.Graph.User.SendMail it working as expected

**Expected behavior**
Email is sent from the current logged in user.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows Server
 - Browser : chrome 
 - Version: 110.0.5481.178

**Additional context**

**Comment by Dale-Dr** [comment]
This is the Code:
 var requestBody = new Microsoft.Graph.Me.SendMail.SendMailPostRequestBody
            {

                Message = new Message
                {                   
                    Subject = subject,
                    Body = new ItemBody
                    {
                        ContentType = BodyType.Html,
                        Content = emailBody
                    },
                    ToRecipients = new List<Recipient>()
                    {
                        new Recipient
                        {
                            EmailAddress = new EmailAddress
                            {
                                Address = nameSendTo
                            }
                        }
                    },
                },
                SaveToSentItems = true,
            };

            try
            {
                log.LogInformation($"In the try catch in send email");

                // Send the email
               // await graphServiceClient.Users[userName].SendMail.PostAsync(requestBody, null);
                await graphServiceClient.Me.SendMail.PostAsync(requestBody);

            }

**Comment by andrueastman** [comment]
Thanks for raising this @Dale-Dr 

Any chance you can confirm the error you are receiving when you handle the API error as documented at the link below?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v5.md#error-handling

**Comment by Dale-Dr** [comment]
Hi,

This is the error code and message:

Microsoft.Graph.Models.ODataErrors.MainError.Code.get returned         "BadRequest"   string
Microsoft.Graph.Models.ODataErrors.MainError.Message.get returned  "/me request is only valid with delegated authentication flow."     String

I have added the API Permissions to the app..
***@***.***

**Comment by andrueastman** [comment]
Hey @Dale-Dr,

I believe the error you are getting is due to your app using application permissions rather than delegated permissions.
As the application context does not have a "user" that the application is acting as, you cannot call the `/me` endpoint. To do this you would need to acquire a user token so that the `/me` call is associated with that user. 

To do this, you would need to authenticate using one of the public client flows that involves acquiring tokens for a user.

**Comment by Dale-Dr** [comment]
Hi Eastman,

Strange as I am logging into the app.

I have also have added the following delegated  API Permissions:
Mail.Send
Mail.ReadWrite

**Comment by Dale-Dr** [comment]
Question: how do we setup the "Authorization code provider". in the doco it only has this:
// For authorization code flow, the user signs into the Microsoft
// identity platform, and the browser is redirected back to your app
// with an authorization code in the query parameters
var authorizationCode = "AUTH_CODE_FROM_REDIRECT";

I can't seem to find any help documentation on how to set this up?

**Comment by andrueastman** [comment]
> Strange as I am logging into the app.
I have also have added the following delegated  API Permissions:
Mail.Send
Mail.ReadWrite

Any chance you are able to share a code sample of how you are creating the `GraphServiceClient` instance to help us understand this better?

Any chance you are using one of the methods available at https://learn.microsoft.com/en-us/graph/sdks/choose-authentication-providers?view=graph-rest-1.0&tabs=CS

**Comment by Dale-Dr** [comment]
Hi,

I’m using the “Client credentials provider” option from the link you provided… I’ve realised that now it’s the wrong one so I’m now trying the “Authorization code provider” option.  But I’m having issues finding help on how to get the “authorizationCode”, from this step:
var authorizationCode = "AUTH_CODE_FROM_REDIRECT";

**Comment by Dale-Dr** [comment]
Hi Any advise on how to get the authorizationCode

**Comment by NN87** [comment]
Hi Dale,
I've a similar issue.
I'm still getting a bit confused on how and if is possibile to send an email, automatically from an application, that follows a specific autohization flow, without then a human interaction.
I've successfully get Application token, for application only, get Delegated user access token, but in both cases, when then I try to send an email wtih graphClient.Me.SendMail.PostAsync(requestBody), I get that damned prompt for device authentication.

I'm wondering at this point, if still exists a way to send an email with Graph API, that will not require a real user to manually login when trying to send an email

**Comment by dromer328** [comment]
> Hi Any advise on how to get the authorizationCode

Any success on "AUTH_CODE_FROM_REDIRECT"  🤔

**Comment by Dale-Dr** [comment]
Hi,

No never got any advice on it….
