### ISSUE TITLE
LargeFileUploadTask randomly throws error

### ISSUE THREAD

**Issue by kishanhathiwala** [microsoftgraph/msgraph-sdk-dotnet#1741]
**Describe the bug**
Explanation of the my code below is it picks the file and uploads it to Microsoft Personal OneDrive and deletes the local file. But somehow it randomly generates an error. 

Can someone please guide me?

**To Reproduce**
```
    var props = new DriveItemUploadableProperties {
        Name = @$"{values.Item2}",
        FileSystemInfo = new FileSystemInfo {
            LastModifiedDateTime = new DateTimeOffset(item.LastModifiedDateTime.Value.UtcDateTime)
        },
        AdditionalData = new Dictionary<string, object> { { "@microsoft.graph.conflictBehavior", "rename" } },
        OdataType = "microsoft.graph.driveItemUploadableProperties"
    };

    var uploadSession = await destinationGraphServiceClient
        .Drives[driveId]
        .Items["root"]
        .ItemWithPath(@$"{values.Item1}/{values.Item2}")
        .CreateUploadSession.PostAsync(new CreateUploadSessionPostRequestBody { Item = props });

    var progress = new Progress<long>(p => {
        Console.WriteLine($"Uploaded {p} bytes of {item.Size} bytes");
    });

    using var fs = new FileStream(values.Item2, FileMode.Open); //This is line 149
    var largeFileUpload = new LargeFileUploadTask<DriveItem>(uploadSession, fs, 320 * 1024);
    var result = await largeFileUpload.UploadAsync(progress);

    Console.WriteLine(result.UploadSucceeded
        ? $"Uploaded completed for file: {result.ItemResponse.Name} with fileId: {result.ItemResponse.Id}"
        : $"Upload failed for file: {item.Name}");

     Thread.Sleep(2000);
     File.Delete(item.Name!);
```

Error:
```
Unhandled exception. System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.ObjectDisposedException: Cannot access a closed Stream.
Object name: 'ReadOnlySubStream'.
   at System.IO.Stream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.StreamToStreamCopy.CopyAsync(Stream source, Stream destination, Int32 bufferSize, Boolean disposeSource, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
   at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.SendRetryAsync(HttpResponseMessage response, RetryHandlerOption retryOption, CancellationToken cancellationToken, ActivitySource activitySource)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.CompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendNoContentAsync(RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.UploadSliceRequestBuilder`1.PutAsync(Stream stream, CancellationToken cancellationToken)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadSliceAsync(UploadSliceRequestBuilder`1 uploadSliceRequestBuilder, ICollection`1 exceptionTrackingList, CancellationToken cancellationToken)
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries, CancellationToken cancellationToken)
   at Program.<<Main>$>g__UploadItem|0_7(GraphServiceClient destinationGraphServiceClient, String driveId, DriveItem item, Tuple`2 values) in /src/OneDriveTransfer/Program.cs:line 149
```

**Expected behavior**
File should be uploaded.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux docker
 - Browser: Console application
 - Version: 5.1.0

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by andrueastman** [comment]
Thanks for raising this @kishanhathiwala 

Any chance you have any luck if you replace 

```cs
using var fs = new FileStream(values.Item2, FileMode.Open); //This is line 149
```

with

```cs
using var fileStream = System.IO.File.OpenRead(values.Item2);
```

**Comment by kishanhathiwala** [comment]
Hi @andrueastman 

I did try your suggestion but it still failing.

```
info: Program[0]
      21-03-2023 05:19:03 - Uploaded 4830003199 bytes of 6732538880 bytes
info: Program[0]
      21-03-2023 05:19:03 - Uploaded 4830330879 bytes of 6732538880 bytes
info: Program[0]
      21-03-2023 05:19:04 - Uploaded 4830658559 bytes of 6732538880 bytes
fail: Program[0]
      21-03-2023 05:19:26 - System.Net.Http.HttpRequestException: Error while copying content to a stream.
       ---> System.ObjectDisposedException: Cannot access a closed Stream.
      Object name: 'ReadOnlySubStream'.
         at System.IO.Stream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
         at System.Net.Http.StreamToStreamCopy.CopyAsync(Stream source, Stream destination, Int32 bufferSize, Boolean disposeSource, CancellationToken cancellationToken)
      --- End of stack trace from previous location ---
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpContent.<CopyToAsync>g__WaitAsync|56_0(ValueTask copyTask)
         at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.SendRetryAsync(HttpResponseMessage response, RetryHandlerOption retryOption, CancellationToken cancellationToken, ActivitySource activitySource)
         at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.CompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims)
         at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendNoContentAsync(RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
         at Microsoft.Graph.UploadSliceRequestBuilder`1.PutAsync(Stream stream, CancellationToken cancellationToken)
         at Microsoft.Graph.LargeFileUploadTask`1.UploadSliceAsync(UploadSliceRequestBuilder`1 uploadSliceRequestBuilder, ICollection`1 exceptionTrackingList, CancellationToken cancellationToken)
         at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries, CancellationToken cancellationToken)
         at Program.<<Main>$>g__UploadItem|0_8(GraphServiceClient destinationGraphServiceClient, String driveId, DriveItem item, Tuple`2 values, ILogger logger) in /src/OneDriveTransfer/Program.cs:line 163
```

and this is the code
```
static async Task UploadItem(GraphServiceClient destinationGraphServiceClient, string driveId, DriveItem item,
    Tuple<string, string> values, ILogger logger) {
    while (true) {
        try {
            var props = new DriveItemUploadableProperties {
                Name = @$"{values.Item2}",
                FileSystemInfo = new FileSystemInfo {
                    LastModifiedDateTime = new DateTimeOffset(item.LastModifiedDateTime.Value.UtcDateTime),
                    CreatedDateTime = new DateTimeOffset(item.CreatedDateTime.Value.UtcDateTime),
                },
                AdditionalData = new Dictionary<string, object> { { "@microsoft.graph.conflictBehavior", "replace" } },
                OdataType = "microsoft.graph.driveItemUploadableProperties"
            };

            var uploadSession = await destinationGraphServiceClient
                .Drives[driveId]
                .Items["root"]
                .ItemWithPath(@$"{values.Item1}/{values.Item2}")
                .CreateUploadSession.PostAsync(new CreateUploadSessionPostRequestBody { Item = props });

            var progress = new Progress<long>(p => {
                logger.LogInformation("{date} - Uploaded {p} bytes of {size} bytes", DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss"), p, item.Size);
            });

            using (var fs = File.OpenRead(values.Item2)) {
                var largeFileUpload = new LargeFileUploadTask<DriveItem>(uploadSession, fs, 320 * 1024);
                var result = await largeFileUpload.UploadAsync(progress);

                if (result.UploadSucceeded)
                    logger.LogInformation("{date} - Uploaded completed for file: {path}/{name} with fileId: {fileId}", DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss"), result.ItemResponse.ParentReference?.Path, result.ItemResponse.Name, result.ItemResponse.Id);
                else
                    logger.LogInformation("{date} - Upload failed for file: {file}", DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss"), item.Name);
            }
            break;
        } catch (Exception ex) {
            logger.LogError("{date} - {error}", DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss"), ex);
        }
    }
} //this is line 163
```

The reason I wrote in loop is, it occurs randomly and if given another try, it uploads successfully. But I am stuck now as this is very large file (approx 6.5 GB) and error is thrown after uploading random bytes, meaning previously it occurred after uploading more than 5GB but this time it stopped after uploading approx 4.8GB. So retrying the same file is not helping. 

I am quite stuck and cannot finish uploading till the solution is found or use another approach.

Cheers,

**Comment by andrueastman** [comment]
Thanks for the extra information @kishanhathiwala 

I believe you do not need to recreate the upload session and re-open the file in the event a transient error occurs. In such an event you can simply call `largeFileUpload.ResumeAsync(progress)`; while still re-using the task. 

Any chance you can try out a refactored version as below and confirm if this works out for you? Also, as the file you plan on uploading is very large, I would suggest using large chunk sizes so that the number of slices/requests aren't too many maybe something like `50 * 320 * 1024` or `15 * 320 * 1024`?

```cs
    static async Task UploadItem(GraphServiceClient destinationGraphServiceClient, string driveId, DriveItem item,
    Tuple<string, string> values, ILogger logger)
    {
        var props = new DriveItemUploadableProperties
        {
            Name = @$"{values.Item2}",
            FileSystemInfo = new Microsoft.Graph.Models.FileSystemInfo
            {
                LastModifiedDateTime = new DateTimeOffset(item.LastModifiedDateTime.Value.UtcDateTime),
                CreatedDateTime = new DateTimeOffset(item.CreatedDateTime.Value.UtcDateTime),
            },
            AdditionalData = new Dictionary<string, object> { { "@microsoft.graph.conflictBehavior", "replace" } },
            OdataType = "microsoft.graph.driveItemUploadableProperties"
        };

        var uploadSession = await destinationGraphServiceClient
                    .Drives[driveId]
                    .Items["root"]
                    .ItemWithPath(@$"{values.Item1}/{values.Item2}")
                    .CreateUploadSession.PostAsync(new CreateUploadSessionPostRequestBody { Item = props });

        var progress = new Progress<long>(p => {
            logger.LogInformation("{date} - Uploaded {p} bytes of {size} bytes", DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss"), p, item. Size);
        });

        using var fs = File.OpenRead(values.Item2);
        var largeFileUpload = new LargeFileUploadTask<DriveItem>(uploadSession, fs, 50 * 320 * 1024, destinationGraphServiceClient.RequestAdapter);

        bool isRetry = false;
        while (true)
        {
            try
            {
                var result = isRetry ? await largeFileUpload.ResumeAsync(progress)  : await largeFileUpload.UploadAsync(progress);
                if (result.UploadSucceeded)
                    logger.LogInformation("{date} - Uploaded completed for file: {path}/{name} with fileId: {fileId}", DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss"), result.ItemResponse.ParentReference?.Path, result.ItemResponse.Name, result.ItemResponse.Id);
                else
                    logger.LogInformation("{date} - Upload failed for file: {file}", DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss"), item.Name);
                break;
            }
            catch (Exception ex)
            {
                isRetry = true;
                logger.LogError("{date} - {error}", DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss"), ex);
            }
        }
    }
```

**Comment by kishanhathiwala** [comment]
Hi @andrueastman 

You are a gem 💎 

I just have one doubt that resuming uploading won't corrupt my file. Closing it for now.

Many thanks,
