### ISSUE TITLE
Graph API SDK v5 Batch request is not setting the request body

### ISSUE THREAD

**Issue by alrios-ms** [microsoftgraph/msgraph-sdk-dotnet#1850]
Please provide the following (and please check them off the list with [x]) before submitting this issue:
- [ ] Expected behavior. Please provide **links to the specific [Microsoft Graph documentation](https://developer.microsoft.com/en-us/graph/docs/concepts/overview)** you used to determine the expected behavior. 
- [ ] Actual behavior. Provide error codes, stack information, and a [Fiddler](http://www.telerik.com/fiddler) capture of the request and response (please remove personally identifiable information before posting).
- [ ] Steps to reproduce the behavior. Include your code, IDE versions, client library versions, and any other information that might be helpful to understand your scenario.

### Expected behavior
I am using Microsoft.Graph 5.7.0 to create thousands of users using batching, which works fine until I get throttled, after that the body of new BatchRequestStep is not being set.

I have included a small C# solution to reproduce the issue.

This is the documentation I used.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/366662e338fcf4edc414fefc8a5dcbc4ad218b90/docs/upgrade-to-v5.md#batch-requests

I tried using  batchRequestContent.NewBatchWithFailedRequests per the documentation code sample, however it did not work for me as I am always getting this error so I am manually checking the status codes and creating the new batchRequestContent.
<img width="610" alt="image" src="https://user-images.githubusercontent.com/70599097/233500265-e72564f5-0485-4422-8a49-5c7e41ac52f7.png">

This is an extract of how the request looks like using fiddler:
```
 {
    "requests":
    [
        {
            "id": "3fe67305-1340-4126-b634-cc6da3d6cad7",
            "url": "/users",
            "method": "POST",
            "headers":
            {
                "Accept": "application/json",
                "Authorization": "Bearer token...",
                "Content-Type": "application/json"
            },
            "body":
            {
                "@odata.type": "#microsoft.graph.user",
                "accountEnabled": true,
                "displayName": "user 4501",
                "mailNickname": "user4501",
                "onPremisesImmutableId": "123",
                "passwordProfile":
                {
                    "password": "123"
                },
                "usageLocation": "US",
                "userPrincipalName": "user4501@tenantdomain.onmicrosoft.com"
            }
        }
        ...
```

### Actual behavior

After getting throttled the code waits before sending new requests, it recreates the batchRequestContent and the batchContentSteps and sends those that came back with status code 429 from the previous batch request. However I am getting this response for every single batchContentStep 
```
{
    "error":
    {
        "code": "Request_BadRequest",
        "message": "A value is required for property 'displayName' of resource 'User'.",
        "innerError":
        {
            "date": "2023-04-20T21:00:51",
            "request-id": "cc4ff088-eadd-4c67-841b-33e13cf55705",
            "client-request-id": "e1750988-e9a9-42f9-8872-0db64f17118a"
        }
    }
}
```

This is how the batch request looks like from Fiddler, the body is completely empty.
```
{
    "requests":
    [
        {
            "id": "981a22a7-9d99-4397-a31b-82ef2b18b78c",
            "url": "/users",
            "method": "POST",
            "headers":
            {
                "Accept": "application/json",
                "Authorization": "Bearer token",
                "Content-Type": "application/json"
            },
            "body":
            {}
        },
        {
            "id": "db799eb1-6050-4c4f-a276-3e5f96fa53bb",
            "url": "/users",
            "method": "POST",
            "headers":
            {
                "Accept": "application/json",
                "Authorization": "Bearer token",
                "Content-Type": "application/json"
            },
            "body":
            {}
        }
```

### Steps to reproduce the behavior

This requires an AAD application with proper permissions to create users in the tenant.
Permission: User.ReadWrite.All

Set your application and tenant settings in these variables.

            var clientId = "";
            var clientSecret = "";
            var tenantId = "";
            var tenantName = ""; i.e. M365x000000

Run the application.
It will add thousands of users successfully before getting throttled after that you should see the error messages in the console.

[GraphAPIUpdate.zip](https://github.com/microsoftgraph/msgraph-sdk-dotnet/files/11290882/GraphAPIUpdate.zip)

**Comment by alrios-ms** [comment]
The issue seems to be that the object that is passed to ToPostRequestInformation(user) method cannot be reused to create the subsequent retry POST request.

As I mentioned I noticed the issue when resubmitting the requests after getting throttled but this can be easily reproduced using a single object, submitting the same object on different BatchRequestContents one after another.
```
            var user = new User()....
            var batchRequestContent = new BatchRequestContent(graphClient);
            var postRequest = graphClient.Users.ToPostRequestInformation(user);
            var requestId = await batchRequestContent.AddBatchRequestStepAsync(postRequest);
            var batchResponse = await graphClient.Batch.PostAsync(batchRequestContent);
            var responses = await batchResponse.GetResponsesAsync(); // 201 - Created

            batchRequestContent = new BatchRequestContent(graphClient);
            postRequest = graphClient.Users.ToPostRequestInformation(user);
            requestId = await batchRequestContent.AddBatchRequestStepAsync(postRequest);
            batchResponse = await graphClient.Batch.PostAsync(batchRequestContent);
            responses = await batchResponse.GetResponsesAsync(); // 400 - Bad Request
```

First requests looks like fine:
```
{
    "requests":
    [
        {
            "id": "998a9fab-5349-428b-99bf-229515b1f110",
            "url": "/users",
            "method": "POST",
            "headers":
            {
                "Accept": "application/json",
                "Authorization": "Bearer toekn...",
                "Content-Type": "application/json"
            },
            "body":
            {
                "@odata.type": "#microsoft.graph.user",
                "accountEnabled": true,
                "displayName": "test 1",
                "mailNickname": "test1",
                "onPremisesImmutableId": "1",
                "passwordProfile":
                {
                    "password": "1"
                },
                "usageLocation": "US",
                "userPrincipalName": "test1@tenantname.onmicrosoft.com"
            }
        }
    ]
}
```

Second request has an empty body.
```
{
    "requests":
    [
        {
            "id": "717b13a9-be38-4c34-a3fc-262ecc892ced",
            "url": "/users",
            "method": "POST",
            "headers":
            {
                "Accept": "application/json",
                "Authorization": "Bearer token...",
                "Content-Type": "application/json"
            },
            "body":
            {}
        }
    ]
}
```

The workaround I found is to clone the user object and use that in the second request, then the request body is properly set;
And I get the expected result for this scenario as the user has been created already.
```
{
    "responses":
    [
        {
            "id": "42eb46d4-da3d-436d-8277-09253f8f4076",
            "status": 400,
            "headers":
            {
                "Cache-Control": "no-cache",
                "x-ms-resource-unit": "1",
                "Content-Type": "application/json"
            },
            "body":
            {
                "error":
                {
                    "code": "Request_BadRequest",
                    "message": "Another object with the same value for property userPrincipalName already exists.",
                    "details":
                    [
                        {
                            "code": "ObjectConflict",
                            "message": "Another object with the same value for property userPrincipalName already exists.",
                            "target": "userPrincipalName"
                        }
                    ],
                    "innerError":
                    {
                        "date": "2023-04-21T17:13:12",
                        "request-id": "752bfab6-a5ba-4e68-bb98-e2bedc35b029",
                        "client-request-id": "31ca97d2-47ef-41b2-b5f9-c6d93c4df8cd"
                    }
                }
            }
        }
    ]
}
```

**Comment by WolfgangHG** [comment]
Still happens with 5.27.0.

Just for the records, the full error from the initial bugreport (after sending "batchRequestContent.NewBatchWithFailedRequests" through "PostBatch") is this:

```
Message: Microsoft.Graph.ClientException: Unable to deserialize content.

StackTrace:
   at Microsoft.Graph.BatchRequestContent.GetRequestContentAsync(HttpRequestMessage request)
   at Microsoft.Graph.BatchRequestContent.WriteBatchRequestStepAsync(BatchRequestStep batchRequestStep, Utf8JsonWriter writer)
   at Microsoft.Graph.BatchRequestContent.GetBatchRequestContentAsync()
   at Microsoft.Graph.Core.Requests.BatchRequestBuilder.ToPostRequestInformationAsync(BatchRequestContent batchRequestContent)
   at Microsoft.Graph.Core.Requests.BatchRequestBuilder.PostAsync(BatchRequestContent batchRequestContent, CancellationToken cancellationToken, Dictionary`2 errorMappings)
   at Microsoft.Graph.Core.Requests.BatchRequestBuilder.PostAsync(BatchRequestContentCollection batchRequestContentCollection, CancellationToken cancellationToken, Dictionary`2 errorMappings)
   at ...my own code...

  InnerException (System.ObjectDisposedException) : Tiefe 1
  Message: System.ObjectDisposedException: Cannot access a closed Stream.

  StackTrace:
   at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Text.Json.JsonDocument.ReadToEndAsync(Stream stream, CancellationToken cancellationToken)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
   at Microsoft.Graph.BatchRequestContent.GetRequestContentAsync(HttpRequestMessage request)

```

So, this makes "NewBatchWithFailedRequests" actually useless....

**Comment by WolfgangHG** [comment]
I hope I found a more generic workaround (instead of recreating the request for each retry). This is necessary for me, because several pieces of code create batch requests, and a helper method makes the "PostBatch" call and evaluates  the results. This helper method cannot recreate the request itself.

The only thing necessary is to store the "Content" memory stream in a list of byte arrays and create a new "StreamContent" for each BatchRequestStep.



Creating the batch request ins done somewhere else in my code, I just provide the BatchRequestContentCollection and a list of step Ids to a helper method.
```
BatchRequestContentCollection batchRequestContent = new BatchRequestContentCollection(graphClient);
List<string> listStepIds = new List<string>();

for (...)
{
  Event eventX = CreateEvent(...);
  RequestInformation addEventRequest = graphClient.Users["me@contoso.com"].Calendar.Events.ToPostRequestInformation (eventX);

  string requestStepId = await batchRequestContent.AddBatchRequestStepAsync(addEventRequest);
  listStepIds.Add(requestStepId);
}
```

This is the code of my helper method:
```
//Before sending the batch, store all binary data and the content types of the original requests:
List<byte[]> listStreams = new List<byte[]>();
List<MediaTypeHeaderValue> listContentTypes = new List<MediaTypeHeaderValue>();
foreach (KeyValuePair<string, BatchRequestStep> step in batchRequestContent.BatchRequestSteps)
{
  if (step.Value.Request.Content is StreamContent streamContent)
  {
    //Read content (using Reflection)...
    FieldInfo fieldContent = streamContent.GetType().GetField("_content", BindingFlags.Instance | BindingFlags.NonPublic);
    Stream stream = (Stream)fieldContent.GetValue(streamContent);
    if (stream is MemoryStream memStream)
    {
      listStreams.Add(memStream.ToArray());
    }

    listContentTypes.Add(step.Value.Request.Content.Headers.ContentType);
  }
}

//Now post the batch:
BatchResponseContentCollection responseContent = await PostBatch(graphClient, batchRequestContent);



//Get failed requests and create a new BatchRequest:
BatchRequestContentCollection batchRequestContentRetry = new BatchRequestContentCollection(graphClient);

List<string> listStepIdsRetry = new List<string>();

for (int intIndexStep = 0; intIndexStep < listStepIds.Count; intIndexStep++)
{
  string strStepId = listStepIds[intIndexStep];

  HttpResponseMessage responseMessage = await responseContent.GetResponseByIdAsync(strStepId);

  //This would also detect broken requests - we actually need 429 (Throttling) and maybe 503 (ServiceUnavailable)
  if (responseMessage.IsSuccessStatusCode == false)
  {
    //Create a new BatchRequestStep based on the failed step:
    string stepIdRetry = batchRequestContentRetry.AddBatchRequestStep(batchRequestContent.BatchRequestSteps[strStepId].Request);

    //Create a new StreamContent from initially saved request:
    StreamContent contentRetry = new StreamContent(new MemoryStream(listStreams[intIndexStep]));
    //Restore content type:
    contentRetry.Headers.ContentType = listContentTypes[intIndexStep];
    //Set it to the new request step:
    batchRequestContentRetry.BatchRequestSteps[stepIdRetry].Request.Content = contentRetry;

    listStepIdsRetry.Add(stepIdRetry);
  }
  responseMessage.Dispose();
}


//Resend:
BatchResponseContentCollection responseContentRetry = await PostBatch(graphClient, batchRequestContentRetry);
```

I don't know how this code behaves for requests that don't have a content, as I tested it only for the request to add calendar events. And the previous comment by @alrios-ms said that he could not reuse an existing object, so maybe this kind of request would also fail with my workaround...
