### ISSUE TITLE
ODataError when requesting the singleValueExtendedProperties of a mail

### ISSUE THREAD

**Issue by Danny4021** [microsoftgraph/msgraph-sdk-dotnet#1950]
Hello,

when I try to get the `SingleValueExtendedProperties` of an E-Mail, I get the following error: 
```
Microsoft.Graph.Models.ODataErrors.ODataError: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
```

I make the request like this:
```c#
string expandQuery = Uri.EscapeDataString("singleValueExtendedProperties($filter=id eq String {8849fa11-aad2-4273-8243-56cf84ffc391} Name My-Name)");

var additionalMessageData = await _client
		.Users[mailAddress]
		.Messages[message.Id]
	        .GetAsync(request => {
                    request.QueryParameters.Expand = new[] { expandQuery };
		});
```

This throws the exception mentioned.
So did I do anything wrong? I tried to do it exactly as in the [doc-example](https://learn.microsoft.com/en-us/graph/api/singlevaluelegacyextendedproperty-get?view=graph-rest-1.0&tabs=csharp) but it doesn't work no matter what I try and the error message doesn't tell me much about what went wrong. It worked before I updated the SDK to version 5.11 (I previously used 4.x)

**Comment by andrueastman** [comment]
Thanks for raising this @Danny4021 

Any chance you are able the share the error information when you follow the guidance at the link below on error handling?
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md

I would also suggest trying to remove the `Uri.EscapeDataString` as well as the SDK now uses a url templating mechanism that will correctly encode the url for you and this may cause double encoding. This means that you can simply pass the string as is and the encoding will be done for you.
