### ISSUE TITLE
GraphServiceClient.AuthenticationProvider is missing after update to 5.x

### ISSUE THREAD

**Issue by looc** [microsoftgraph/msgraph-sdk-dotnet#1961]
Hi
This my not be a bug nut i cant find any information to why it stop working.

I have a function to do a graph request to an endpoint that is not in the sdk using the same GraphServiceClient as with ex graphClinet.Teams or graphClient.Me.
I have been using this code with success fore some time, but after update of Microsoft.Graph form 4.x to  5.x the GraphClient.AuthenticationProvider is not longer available.
I cant figure out how to rewrite it to work with 5.x

```
using (HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, url))
{
    // Authenticate (add access token) our HttpRequestMessage
    await GraphClient.AuthenticationProvider.AuthenticateRequestAsync(request);

    // Send the request and get the response.
    HttpResponseMessage response = await GraphClient.HttpProvider.SendAsync(request);

    // Process the response
    var jsonStr = await response.Content.ReadAsStringAsync();

    //return JsonConvert.DeserializeObject<T>(jsonStr.Result);

    return jsonStr;
}
```

**Comment by andrueastman** [comment]
Thanks for raising this @looc 

As the V5 of the SDK uses the Kiota abractions, requests are now represented using the `RequestInformation` and the request adapter will handle the authentication for you. 

You should therefore be able to achieve the same with 

```cs
string url = "https://graph.microsoft.com/v1.0/me";
var request = new RequestInformation 
{
    HttpMethod = Method.GET,
    URI = new Uri(url)
};
// RequestAdapter will authenticate the request with the configured auth provider.
var jsonStr = await graphClient.RequestAdapter.SendPrimitiveAsync<string>(request);
```

**Comment by looc** [comment]
Thanx, but this gives the error:

```
Value cannot be null. (Parameter 'input')

at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.startTracingSpan(RequestInformation requestInfo, String  
methodName)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendPrimitiveAsync>d__21`1.MoveNext()
   at DownloadO365Statistics.Services.O365GraphService.<GetCustomEndpointAsync>d__17.MoveNext() in  C:\Users\cc\Documents\Visual Studio rojects\xx\DownloadO365Statistics\DownloadO365Statistics\Services\O365GraphService.cs:line 129
   at DownloadO365Statistics.Program.<Main>d__1.MoveNext() in C:\Users\cc\Documents\Visual Studio rojects\xx\DownloadO365Statistics\DownloadO365Statistics\Program.cs:line 28
```

**Comment by looc** [comment]
Sure..
That returns error:

 ```
The server returned an unexpected status code and no error factory is registered for this code: 400

   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<ThrowIfFailedResponse>d__28.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendPrimitiveAsync>d__21`1.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendPrimitiveAsync>d__21`1.MoveNext()
   at DownloadO365Statistics.Services.O365GraphService.<GetCustomEndpointAsync>d__17.MoveNext() ....
```

**Comment by andrueastman** [comment]
Any chance you could try with this updated sample? This works from my end? If not you could share the error reported in the catch block?

```cs
try
{
    var request = new RequestInformation
    {
        HttpMethod = Method.GET,
        UrlTemplate = "https://graph.microsoft.com/beta/reports/getTeamsUserActivityTotalCounts(period='D7')"
    };
    var errorMapping = new Dictionary<string, ParsableFactory<IParsable>> {
        {"4XX", ODataError.CreateFromDiscriminatorValue},
        {"5XX", ODataError.CreateFromDiscriminatorValue},
    };
    // RequestAdapter will authenticate the request with the configured auth provider.
    using var reportStream = await graphClient.RequestAdapter.SendPrimitiveAsync<Stream>(request,errorMapping);
    using var streamReader = new StreamReader(reportStream);
    var jsonString = await streamReader.ReadToEndAsync();
}
catch (ODataError e)
{
    Console.WriteLine(e.Error?.Code);
    Console.WriteLine(e.Error?.Message);
    throw;
}
```

**Comment by looc** [comment]
Hi
That works , i think it was mostly error on my side.
I used the endpoint https://graph.microsoft.com/v1.0/me and that gave the 400 error, i never tried with any other url.
After changing endpoint  and also changing to Stream and streamreader i get a json result.

You should add this example to the documentation i really clear things up on how to use  SendPrimitiveAsync

Thanx //Looc
