### ISSUE TITLE
SSL issues on Linux

### ISSUE THREAD

**Issue by TobiasLaving** [microsoftgraph/msgraph-sdk-dotnet#1971]
**Describe the bug**
I am running Manjaro and have issues running the dotnet version of the sdk
I can run python fine, only dotnet is having issues.

Works well on windos

**To Reproduce**
Run this code on Manjaro ( Linux? )
```
using System;
using Azure.Identity;
using Microsoft.Graph;

var credential = new AzureCliCredential();
var graphClient = new GraphServiceClient(credential);

var p = await graphClient.Me.GetAsync();
Console.WriteLine(p);
```

**Expected behavior**
Not crashing

**Output**
```
/home/tobias/dev/trine/playground/Kaos/Kaos/bin/Debug/net7.0/linux-x64/Kaos
Unhandled exception. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.CompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.MeRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /home/tobias/dev/trine/playground/Kaos/Kaos/Program.cs:line 20
   at Program.<Main>(String[] args)
```

**Desktop (please complete the following information):**
 - OS: Manjaro

**Comment by andrueastman** [comment]
Thanks for raising this @TobiasLaving 

To confirm, are you able to perform any requests in C# on your runtime? Any chance you can try the example listed here and confirm if you still get the same error? 
https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-7.0#examples

**Comment by TobiasLaving** [comment]
Hello @andrueastman 
Thanks for a great example to test

Yes, it works well. I'm writing a decent amount of c# code interacting with various web services and have not had ssl issues like these before.

**Comment by andrueastman** [comment]
To help narrow things down do you still get an error on creating and using default httpClient as below?

```cs

            var httpClient = new HttpClient();
            var requestInformation = graphClient.Me.ToGetRequestInformation();
            var requestMessage = await graphClient.RequestAdapter.ConvertToNativeRequestAsync<HttpRequestMessage>(requestInformation);

            var responseString = await httpClient.SendAsync(requestMessage);
            Console.WriteLine(await responseString.Content.ReadAsStringAsync());
```

**Comment by TobiasLaving** [comment]
@andrueastman Sorry for the slow response.

Thanks for the code snippet, the result was the same though

**Comment by andrueastman** [comment]
Thanks for the feedback here @TobiasLaving,

I believe you can clean this up as below.

```cs
            var credential = new AzureCliCredential();
            var httpClient = GraphClientFactory.Create(finalHandler: new HttpClientHandler()
            {
                ServerCertificateCustomValidationCallback = (message, certificate2, arg3, arg4) => true
            });
            var graphClient = new GraphServiceClient(httpClient, new Microsoft.Graph.Authentication.AzureIdentityAuthenticationProvider(credential));

            var user = await graphClient.Me.GetAsync();
```
