### ISSUE TITLE
CreateUploadSession throwing invalidRequest

### ISSUE THREAD

**Issue by kishanhathiwala** [microsoftgraph/msgraph-sdk-dotnet#1998]
**Describe the bug**
For some reason, I keep getting `invalidRequest`. And the strange thing is when I debug and run the code of line 214 manually in Visual Studio's QuickWatch, the code does not throw any exception. Please see my code below:

**To Reproduce**
```
private static async Task<UploadSession?> GetUploadSession(BaseGraphServiceClient client, string driveId, FileInfo fileInfo, string path)
    {
        return await PerformTask(async () =>
        {
            var props = new DriveItemUploadableProperties
            {
                Name = fileInfo.Name,
                FileSystemInfo = new FileSystemInfo
                {
                    LastModifiedDateTime = new DateTimeOffset(fileInfo.LastWriteTimeUtc),
                    CreatedDateTime = new DateTimeOffset(fileInfo.CreationTimeUtc)
                },
                AdditionalData = new Dictionary<string, object> { { "@microsoft.graph.conflictBehavior", "replace" } },
                OdataType = "microsoft.graph.driveItemUploadableProperties"
            };

           //this block is line 214
            return await client
                 .Drives[driveId]
                 .Items["root"]
                 .ItemWithPath(string.IsNullOrWhiteSpace(path) ? fileInfo.Name : $"{path}/{fileInfo.Name}")
                 .CreateUploadSession
                 .PostAsync(new CreateUploadSessionPostRequestBody { Item = props });
        }, Serialize(new
        {
            FunctionName = nameof(GetUploadSession),
            DriveId = driveId,
            FileInfo = fileInfo.FullName
        }));
    }

private static async Task<T> PerformTask<T>(Func<Task<T>> value, string jsonData, int retryCount = 10)
    {
        var count = 0;
        while (true)
        {
            try
            {
                if (count > retryCount)
                {
                    throw new Exception("Maximum retry reached.");
                }

                return await value(); //this is line 240 (mentioned in error)
            }
            catch (ODataError ex)
            {
                _logger.LogError("{date} - ODataError occurred. Error Message: {message}. Error: {error}. JsonData: {jsonData}", DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss"), JsonSerializer.Serialize(ex.Error), ex, jsonData);

                if (count <= retryCount)
                {
                    await Task.Delay(2000);
                }
                else
                {
                    throw new Exception("Maximum retry reached.");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("{date} - Error occurred. Error: {ex}. JsonData: {jsonData}", DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss"), ex, jsonData);

                if (count <= retryCount)
                {
                    await Task.Delay(2000);
                }
                else
                {
                    throw new Exception("Maximum retry reached.");
                }
            }

            count++;
        }
    }

private static string Serialize(object value) => JsonSerializer.Serialize(value);
```
The error I get is 
```
04-07-2023 21:04:47 - ODataError occurred. Error Message: {"AdditionalData":{"innerError":{"date":"2023-07-04T11:04:47","request-id":"9659727f-fe47-4321-9acc-b7e610c4fe95","client-request-id":"e16b44d5-1d19-4ed8-888b-b2a5bb937188"}},"BackingStore":{"InitializationCompleted":true,"ReturnOnlyChangedValues":false},"Code":"invalidRequest","Details":null,"Innererror":null,"Message":"Invalid request","Target":null}. Error: Microsoft.Graph.Models.ODataErrors.ODataError: Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
         at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes)
         at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
         at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
         at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
         at OneDriveUploader.Program.<>c__DisplayClass14_0.<<GetUploadSession>b__0>d.MoveNext() in D:\Kishan\OneDriveUploader\OneDriveUploader\Program.cs:line 214
      --- End of stack trace from previous location ---
         at OneDriveUploader.Program.PerformTask[T](Func`1 value, String jsonData, Int32 retryCount) in D:\Kishan\OneDriveUploader\OneDriveUploader\Program.cs:line 240
```

**Expected behavior**
I should be getting UploadSession

**Screenshots**
This is when I run line 214 code block in quick watch 
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/29030616/63263040-9e5f-4178-bc72-cadbb6be1308)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Desktop C# console app
 - Version dotnet core 7

**Additional context**

**Comment by andrueastman** [comment]
Thanks for raising this @kishanhathiwala,

Any chance you could share the version of the SDK you are using when this occurs? 
Could you also confirm that the URL is built correctly when you check it as below before the aforementioned line?

```cs
            var requestInfo = client
                .Drives[driveId]
                .Items["root"]
                .ItemWithPath(string.IsNullOrWhiteSpace(path) ? fileInfo.Name : $"{path}/{fileInfo.Name}")
                .CreateUploadSession
                .ToPostRequestInformation(new CreateUploadSessionPostRequestBody { Item = props });

            Console.WriteLine("URL : " + requestInfo.URI.OriginalString);
```

**Comment by kishanhathiwala** [comment]
SDK version:
<PackageReference Include="Azure.Identity" Version="1.8.2" />
<PackageReference Include="Microsoft.Graph" Version="5.3.0" />

Output in the console is `URL: https://graph.microsoft.com:443/v1.0/drives/b%210hKnP4pQDUWZ2GavRuBzbpMcWntl9wlNsRFquvTnnSXyyQxHuWJWS4GuhLVf2woM/items/root:/Screenshots/Screenshot%20(1).png:/microsoft.graph.createUploadSession`

I hope I have answer your questions.

**Comment by andrueastman** [comment]
@kishanhathiwala I notice that the name in the request body is set as `Name = fileInfo.Name,` which does not contain the path that is used in the url if the path parameter is set. Thus the url will contain the full path but the body will have only the name and will thus possibly result in a conflict. 

Any chance the request works out if you do not set the name in the body and simply rely on the path name? I believe the OdataType property need not be set as well. 

```cs
var props = new DriveItemUploadableProperties
{
    FileSystemInfo = new FileSystemInfo
    {
        LastModifiedDateTime = new DateTimeOffset(fileInfo.LastWriteTimeUtc),
        CreatedDateTime = new DateTimeOffset(fileInfo.CreationTimeUtc)
    },
    AdditionalData = new Dictionary<string, object> { { "@microsoft.graph.conflictBehavior", "replace" } }
};
```

**Comment by kishanhathiwala** [comment]
@andrueastman your suggestion seems to working. I will close the ticket. Thank you for your help 😄
