### ISSUE TITLE
People Request failed

### ISSUE THREAD

**Issue by Mimetis** [microsoftgraph/msgraph-sdk-dotnet#203]
An error occured on the `People` request async task :

```
var peopleRequest = graphServiceClient.Users[user.UserPrincipalName].People.Request();
var team = await peopleRequest.GetAsync();

```
Actually, the fiddler response is correct, and JSON seems to be well formated.  
Error raised is :

`Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path 'personType'`

**Comment by MIchaelMainer** [comment]
I can't reproduce the error. I wonder if you're getting back a bad value in personType.

Can you run this: `var people = await graphClient.Me.People.Request().Select("personType").GetAsync();`

Can you provide the response fiddler trace and pretty print and post it here?

**Comment by MIchaelMainer** [comment]
Please reopen this issue when provide the Fiddler response.

**Comment by Mrcl1450** [comment]
I'm getting the same error.
http://prntscr.com/jco77a

**Comment by Mrcl1450** [comment]
Ok I guess it was the beta graph.
Using 1.0 http://prntscr.com/jco8yn

**Comment by michael-hawker** [comment]
Yeah, I'm trying to use the beta end-point and get this error as well:

```
Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path 'personType', line 1, position 547.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Graph.DerivedTypeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Microsoft.Graph.DerivedTypeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.Converters.CustomCreationConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Graph.Serializer.DeserializeObject[T](String inputString)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__30`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.UserPeopleCollectionRequest.<GetAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at active_directory_dotnet_native_uwp_v2.MainPage.<LoadDataAsync>d__3.MoveNext() in 
```

Using Graph Explorer you can see in the V1 endpoint you can see this type of structure:
```
           "personType": {
                "class": "Person",
                "subclass": "ImplicitContact"
            }
```

However in the Beta endpoint it's just a string:
```
          "personType": "Person",
```

Looks like there needs to be another JsonConverter which knows how to create a PersonType object from a plain string?

**Comment by michael-hawker** [comment]
@MIchaelMainer can we re-open this issue?

**Comment by MIchaelMainer** [comment]
@michael-hawker I believe the issue is that the PersonType is different in beta versus v1.0 endpoint. Use the Microsoft.Graph.Beta NuGet package to use this entity.

**Comment by michael-hawker** [comment]
@MIchaelMainer ah thanks, I didn't realize there was a separate package, good to know.
