### ISSUE TITLE
HttpRequestException when the client secret is expired

### ISSUE THREAD

**Issue by Danny4021** [microsoftgraph/msgraph-sdk-dotnet#2067]
Hello,

I have the following problem/question:
When I try to make a request via GraphServiceClient with a tenant whose client secret is expired, a HttpRequestException is thrown with the following stacktrace:
```
Exception Info: System.Net.Http.HttpRequestException

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RedirectHandler+<SendAsync>d__5.MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler+<SendAsync>d__7.MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.CompressionHandler+<SendAsync>d__1.MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter+<GetHttpResponseMessage>d__34.MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter+<SendAsync>d__20`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxx]].MoveNext()
```

I'd expect the GraphServiceClient to wrap this exception inside a `ServiceException` (Or at least an `ApiException`) instead of throwing the HttpRequestExceptions without catching it. 

So I'd like to know if this is a bug or intended behaviour by the `GraphServiceClient`

Thank you in advance!

**Comment by andrueastman** [comment]
Thanks for raising this @Danny4021 

Any chance you can share a code sample as well as the SDK version and target runtime you are using when this occurs?

**Comment by Danny4021** [comment]
Hello @andrueastman
thank you for the quick response

I am currently using Graph SDK version 5.19.0 and the target runtime is netstandard2.0 (it is currently not possible for me to update the target runtime)

As for the sample code:
this happens as soon as I try to get the folder of the tenant via page iterator (which is the first call I make after starting the application)

```csharp
MailFolderCollectionResponse folderCollection = await _graphClient
					.Users[mailAddress]
					.MailFolders
					.GetAsync()
					.ConfigureAwait(false));

await _pageIterator.IterateAsync().ConfigureAwait(false);

List<MailFolder> list = new List<MailFolder>();
PageIterator<MailFolder, MailFolderCollectionResponse> pageIterator = PageIterator<MailFolder, MailFolderCollectionResponse>.CreatePageIterator(_graphClient, folderCollection , resource => {
     list.Add(resource);
     return true;
});

while (pageIterator.State != PagingState.Complete) 
{
     await pageIterator .ResumeAsync().ConfigureAwait(false);
}

return list;
```

After looking into the stacktrace again, I realized that the error probably is thrown somewhere inside the `PageIterator`: 

```
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

   at Microsoft.Graph.PageIterator`2+<InterpageIterateAsync>d__25[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxx],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxx]].MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

   at Microsoft.Graph.PageIterator`2+<IterateAsync>d__27[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxx],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxx]].MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

   at Microsoft.Graph.PageIterator`2+<IterateAsync>d__26[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxx],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxx]].MoveNext()

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
```

**Comment by andrueastman** [comment]
Thanks for the extra information @Danny4021,

There is the possibility that the `HttpRequestException` is thrown by the Authprovider when doing the token fetching rather than the graphClient. Any chance you can also share a sample of how you are setting up the graphClient with the relevant auth provider as well?

**Comment by Danny4021** [comment]
Thanks for the quick response @andrueastman 
I am using a custom `IAccessTokenProvider` which looks like this:

```csharp
private const string REDIRECT_URI = "https://login.microsoftonline.com/common/oauth2/nativeclient";
private const string MS_GRAPH_SCOPE_URI = "https://graph.microsoft.com/.default";

public async Task<string> GetAuthorizationTokenAsync(Uri uri, Dictionary<string, object> additionalAuthenticationContext = null, CancellationToken cancellationToken = new CancellationToken()) {
	IConfidentialClientApplication application = ConfidentialClientApplicationBuilder
		.Create(_tenant.AppId)
		.WithTenantId(_tenant.TenantId)
		.WithClientSecret(_tenant.ClientSecret)
		.WithRedirectUri(REDIRECT_URI)
		.Build();

	AuthenticationResult authResult = await application.AcquireTokenForClient(new[] { MS_GRAPH_SCOPE_URI }).ExecuteAsync(cancellationToken).ConfigureAwait(false);
	string token = authResult.AccessToken;

	return token;
}
```

The tenant is initialized via constructor and just holds the relevant authentication information.
I then create the `GraphServiceClient` like this:
```csharp
BaseBearerTokenAuthenticationProvider authProvider = new BaseBearerTokenAuthenticationProvider(new MyCustomTokenProvider(tenant));
var serviceClient = new GraphServiceClient(authProvider);
```

**Comment by andrueastman** [comment]
Thanks for the extra info @Danny4021 

Any chance you can validate the throwing of the exception in the custom `IAccessTokenProvider` by adding a try catch block around 
`AuthenticationResult authResult = await application.AcquireTokenForClient(new[] { MS_GRAPH_SCOPE_URI }).ExecuteAsync(cancellationToken).ConfigureAwait(false);` and checking if the `HttpRequestException` is thrown there?

**Comment by Danny4021** [comment]
Sadly, this error was thrown a while back and the tenant in question has already been replaced. So I currently don't have a tenant with an expired ClientSecret.
Do you know of any method to "create" an expired token for a tenant? 
Also, thank you for your input on this matter, I'll add the `try-catch` statement to the `IAccessTokenProvider` 

If you don't know of any way to create an expired token, I'll close this ticket and create a new one if the problem still persists.

Thank you for your help!

**Comment by andrueastman** [comment]
@Danny4021 Using Microsoft graph you can probably create a new secret as shown in the documentation at the link below. 
https://learn.microsoft.com/en-us/graph/api/application-addpassword?view=graph-rest-1.0&tabs=http

The call would however still need to be authenticated to graph, so the updating of the secret after its expiry would lead to a catch 22 situation if you are using the same secret. So an alternative authentication mechanism may be needed in this scenario. 

Alternatively, you could check the `endDateTime` property of the secret and do this action before the expiry by comparing it against the current time.

https://developer.microsoft.com/en-us/graph/graph-explorer?request=applications%2Facc848e9-e8ec-4feb-a521-8d58b5482e09%2FpasswordCredentials&method=GET&version=v1.0&GraphUrl=https://graph.microsoft.com
