### ISSUE TITLE
[Client bug]: My .NET Framework (4.8.1) application using MS Graph 4.54.0 cannot send emails

### ISSUE THREAD

**Issue by BJMdotNET** [microsoftgraph/msgraph-sdk-dotnet#2080]
**Describe the bug**
My .NET Framework (4.8.1) application using MS Graph 4.54.0 cannot send emails. Authentication works, but when it calls `GraphServiceClient.Users[MailConfiguration.Email.Sender].SendMail(message, SaveToSentItems: true).Request().PostAsync()`, a ServiceException is thrown. 
Unfortunately this exception contains very little information: "StatusCode = [0], Error = [Code: generalException / Message: An error occurred sending the request.], RawResponseBody = []". In the stack trace I find this: "System.Net.Http.WinHttpException: Error 12007 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server name or address could not be resolved'."

**To Reproduce**
I have created two solutions, one in .NET Framework 4.8.1 and one in .NET 6, to show the code I am using. 
They can be found here: https://github.com/BJMdotNET/ms-graph-emails/ .

**Expected behavior**
I expect a mail to be sent. This works perfectly in the .NET 6 solution, and that one contains virtually the same code and uses the same TenantId etc.

**Client version**
4.54.0

**Additional context**
The reason I need this to work is to upgrade an existing application in .NET Framework 4.7.2. Unfortunately, migrating it to .NET 6 is not a feasible solution, it would need to be completely rewritten. I realize the NuGet package has been upgraded to v5 in recent months, but AFAIK that version does not support .NET Framework, hence me using this older version.

**Comment by andrueastman** [comment]
Thanks for raising this @BJMdotNET 

For context, V5 of the SDK can also work with the .Net framework as well and that can be used to make calls.

I notice that the sample app may use proxy settings to fetch the token but this is not passed to the graph client. Any change you get different results if you do something like this?

```cs
            GraphServiceClient = new GraphServiceClient(new StaticClientWithProxyFactory().GetHttpClient());
            GraphServiceClient.AuthenticationProvider = new DelegateAuthenticationProvider(requestMessage =>
            {
                requestMessage.Headers.Authorization =
                    new AuthenticationHeaderValue("Bearer", authenticationResult.AccessToken);

                return Task.FromResult(0);
            });
```

**Comment by BJMdotNET** [comment]
Thank you @andrueastman .

Unfortunately, this doesn't solve the problem, but I now get a different exception:

```
Message: An error occurred sending the request.
 ---> System.ArgumentException: Only HTTP/1.0 and HTTP/1.1 version requests are currently supported.
Parameter name: value
   at System.Net.HttpWebRequest.set_ProtocolVersion(Version value)
   at System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

I'll try a new version using the v5 SDK.

**Comment by BJMdotNET** [comment]
I have created an updated version of the .NET Framework solution using the latest v5 of the SDK, and I get this exception:

```
2023-08-21 17:33:22.9669 Error MsGraphEmailsFramework.exe MsGraphMailService: Exception: An error occurred while sending the request. - Error 12007 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server name or address could not be resolved'. 
2023-08-21 17:33:23.0288 Error MsGraphEmailsFramework.exe MsGraphMailService: Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 12007 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server name or address could not be resolved'.
```

Which seems to be the same as the one I get in the version with v4.

**Comment by andrueastman** [comment]
Thanks for this @BJMdotNET 

To confirm if this issue is caused by the configuration of the client, or an environment issue are you by any chance able to make a successful request if you make a request as below by replacing the code at the link below

https://github.com/BJMdotNET/ms-graph-emails/blob/3cb30fde21e44197f100cdf3f5c5ae747cdc0904/framework-481/MsGraphEmailsFramework/MsGraphMailService.cs#L50C18-L52C57

with the following?

```cs
var sendEmailRequestInformation = graphClient.Users["sender"]
    .SendMail
    .ToPostRequestInformation(sendMailPostRequestBody);
var requestMessage = await graphClient.RequestAdapter.ConvertToNativeRequestAsync<HttpRequestMessage>(sendEmailRequestInformation);

var httpClient = new HttpClient();
var responseMessage = await httpClient.SendAsync(requestMessage);

if (!responseMessage.IsSuccessStatusCode)
{
    throw new Exception($"Failed to send email. Status code: {responseMessage.StatusCode}");
}
```

**Comment by BJMdotNET** [comment]
@andrueastman 

Using your code the app did succeed in sending the email!

**Comment by BJMdotNET** [comment]
@andrueastman Feedback regarding the two alternatives:

- Unfortunately `var httpClient = GraphClientFactory.Create();` resulted in this error:

     `Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 12007 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server name or address could not be resolved'.`

- However, `var httpClient = GraphClientFactory.Create(finalHandler: new HttpClientHandler());` did succeed in sending an email.

**Comment by BJMdotNET** [comment]
@andrueastman I have some more feedback. I delved into the method `var httpClient = GraphClientFactory.Create();` and found that if `finalHandler` is `null`, then `GetNativePlatformHttpHandler(proxy)` would get called to retrieve a handler.

Looking at that method, I presume that this is the code that gets executed (other parts of that method are only relevant to when it is run on IOS etc.):

```
var proxyPolicy = proxy != null ? WindowsProxyUsePolicy.UseCustomProxy : WindowsProxyUsePolicy.UseWinHttpProxy;
return new WinHttpHandler 
   { 
     Proxy = proxy, 
     AutomaticDecompression = DecompressionMethods.None , 
     WindowsProxyUsePolicy = proxyPolicy, 
     SendTimeout = Timeout.InfiniteTimeSpan, 
     ReceiveDataTimeout = Timeout.InfiniteTimeSpan, 
     ReceiveHeadersTimeout = Timeout.InfiniteTimeSpan 
   };
```

On a whim I changed my code to pass the proxy:

```
                var httpClient = GraphClientFactory.Create(null, "v1.0", GraphClientFactory.Global_Cloud, 
                    new WebProxy(MailConfiguration.MsGraph.ProxyAddress)
                    {
                        Credentials = CredentialCache.DefaultCredentials
                    }, null);
```

And this works!

For the record: when I execute `netsh winhttp show proxy`, I get the result `Current WinHTTP proxy settings: Direct access (no proxy server).`

Note that all of my tests were done while I worked from home while being connected to the corporate network using VPN.

**Comment by andrueastman** [comment]
Thanks for the feedback @BJMdotNET and glad to hear it worked out. 

If I understand correctly, the DNS resolution was failing due to missing the proxy config needed for the `WinHttpHandler`. 

> For the record: when I execute netsh winhttp show proxy, I get the result Current WinHTTP proxy settings: Direct access (no proxy server).

I'm not sure why this would occur but my understanding is that `WinHttpHandler` should be using the WinHTTP interface of the host OS. We'll close this for now and feel free to re-open in case of anything else.
