### ISSUE TITLE
Error when searching a specific user in Groups/Members

### ISSUE THREAD

**Issue by bobs619** [microsoftgraph/msgraph-sdk-dotnet#2093]
This is erroring out in V5.
`var members = await _graphServiceClient.Groups[groupId].Members[id].GraphUser.GetAsync()`

In V4 I could do this NO PROBLEM:
`var members = await _graphServiceClient.Groups[groupId].Members[id].Request().GetAsync()
`

Right now, i have do something funky to get this to work.
```var members = await _graphServiceClient.Groups[groupId].Members.GetAsync((requestConfiguration) =>
  {
      requestConfiguration.QueryParameters.Count = true;
      requestConfiguration.QueryParameters.Filter = $"id eq '{id}'";
      requestConfiguration.Headers.Add("ConsistencyLevel", "eventual");
  });
```
Am I doing something wrong?  Please advise.

**Comment by andrueastman** [comment]
Thanks for raising this @bobs619 

Any chance you can share more details the error you get when you call
```cs
var members = await _graphServiceClient.Groups[groupId].Members[id].GraphUser.GetAsync()
```

**Comment by bobs619** [comment]
@andrueastman 

Here's some details...
IDE: VS2022 17.8.0 Preview 1.0
Project: Function APP V4 Isolated
.NET 7SDK

The exception:
```
Microsoft.Graph.Models.ODataErrors.ODataError
  HResult=0x80131500
  Message=Exception of type 'Microsoft.Graph.Models.ODataErrors.ODataError' was thrown.
  Source=Microsoft.Kiota.Http.HttpClientLibrary
  StackTrace:
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<ThrowIfFailedResponse>d__28.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
   at Microsoft.Graph.Groups.Item.Members.Item.GraphUser.GraphUserRequestBuilder.<GetAsync>d__2.MoveNext()
   at blah.DataAccess.GraphApi.GraphApiProvider.<IsGroupMember>d__11.MoveNext() in c:\\blah\xxx\GraphApi\GraphApiProvider.cs:line 256

  This exception was originally thrown at this call stack:
    [External Code]
    blah.DataAccess.GraphApi.GraphApiProvider.IsGroupMember(string, string) in GraphApiProvider.cs
```

**Comment by andrueastman** [comment]
There is a path missing in the metadata here. We would need to add a GET path to the metadata to `'/groups/{group-id}/members/{directoryObject-id}/'` which is missing at the moment.

**Comment by lramosvea** [comment]
✅ Escalated to the owning service team (Groups Graph API) for a metadata/OpenAPI fix.

**ICM draft created (needs submission):** Please use the pre-filled ICM form here: https://mqw39vv3-3001.usw3.devtunnels.ms/trigger?title=Missing+GET+path+in+metadata%3A+%2Fgroups%2F%7Bgroup-id%7D%2Fmembers%2F%7BdirectoryObject-id%7D+breaks+.NET+SDK+v5+member+retrieval+%28businessPhones+%24select+error%29&severity=3&teamId=63136&teamName=Groups+Graph+API&description=Customer+report+from+msgraph-sdk-dotnet%232093%3A+SDK+v5+call+%60Groups%5BgroupId%5D.Members%5Bid%5D.GraphUser.GetAsync%28%29%60+fails+with+OData+error+%60Invalid+property+%27businessPhones%27+specified+in+%24select.%60%0A%0ARepro%3A%0A-+Using+Microsoft.Graph+v5.x+%28reporter+used+5.24.0%29+call%3A%0A++%60await+graphClient.Groups%5BgroupId%5D.Members%5BuserId%5D.GraphUser.GetAsync%28%29%3B%60%0A%0AObserved%3A%0A-+400+BadRequest+%2F+ODataError%3A+Invalid+property+%27businessPhones%27+specified+in+%24select.%0A%0AWorkaround%3A%0A-+Query+members+collection+with+%60%24filter%3Did+eq+%27%7Bid%7D%27%60+and+%60ConsistencyLevel%3A+eventual%60.%0A%0ASuspected+root+cause+%28per+maintainer analysis%29%3A%0A-+Missing+GET+path+in+metadata%2FOpenAPI+for+%60%2Fgroups%2F%7Bgroup-id%7D%2Fmembers%2F%7BdirectoryObject-id%7D%2F%60 (and typed cast path generation).

Related: msgraph-sdk-dotnet#1853 reports the same `businessPhones` $select error on the same route.

Once submitted, we’ll link the ICM ID back here for tracking.

**Comment by lramosvea** [comment]
### Triage summary
Thanks all — this is **not a client-side usage issue**.

**What’s happening**
- `Groups[groupId].Members[id].GraphUser.GetAsync()` in v5 is generated from **OpenAPI/metadata**.
- For this route, the service metadata is missing a **GET** for `GET /groups/{group-id}/members/{directoryObject-id}` (and therefore the typed cast path that the SDK builder relies on). This leads to an incorrect request shape/selection and the service rejects it with:
  - `Invalid property 'businessPhones' specified in $select.`

**Workaround (as reported)**
- Query the members collection and filter by id (plus `ConsistencyLevel: eventual` when required):
  - `GET /groups/{id}/members?$filter=id eq '{memberId}'&$count=true`

**Next step / owning team**
- This needs a **metadata/OpenAPI fix** in the **Groups Graph API** workload so the SDK can be regenerated correctly.
- I’ve escalated to the owning service team; once the ICM is submitted we’ll link the incident ID back here for tracking.

Related: #1853 (same `businessPhones` $select error on the same route).
