### ISSUE TITLE
Graph SDK 5 HTTP request failed with System.IO.InvalidDataException "invalid data while decoding"

### ISSUE THREAD

**Issue by kyzhangZao** [microsoftgraph/msgraph-sdk-dotnet#2205]
To test the graph sdk upgrade change in our testing environment, all the graph calls failed with System.IO.InvalidDataException "invalid data while decoding"

One sample full traces on our end looks like:

> [Exception:System.IO.InvalidDataException: Found invalid data while decoding.
   at System.IO.Compression.DeflateStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Http.StreamToStreamCopy.StartRead()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<GetHttpResponseMessage>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.<SendAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Subscriptions.SubscriptionsRequestBuilder.<PostAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Polly.Retry.AsyncRetryEngine.<ImplementationAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Polly.AsyncPolicy.<ExecuteAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

This error message is not super helpful, and we're not able to understand what's the exactly issue here. But it seems related with the Kiota HTTP dependency being introduced in the upgrade.
As making http request being mentioned https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/feature/5.0/docs/upgrade-to-v5.md#removal-of-request-from-the-fluent-api, I'm following this guidance. Hence need some hints of how to fix this issue.

**Comment by andrueastman** [comment]
Thanks for raising this @kyzhangZao 

Any chance you can provide some more information on the SDK version you are using and the sample code of the request you are making as well as how you are initializing the client?

**Comment by kyzhangZao** [comment]
Hi @andrueastman , I'm using graph sdk Version="5.32.0"

A sample request of fetching group is like `var group = await graphServiceClient.Groups[groupId].GetAsync().ConfigureAwait(false);`

And for graph client initialization 
We have AadAppAuthAccessTokenProvider that implements IAccessTokenProvider interface, and then use BaseBearerTokenAuthenticationProvider with the above access token as parameter.
We also have some customized handlers and create pipeline with those handlers. A HttpClient is being generated with the pipeline as one of the parameter.
We use this constructor 
`public GraphServiceClient(
    HttpClient httpClient,
    IAuthenticationProvider authenticationProvider = null,
    string baseUrl = null):this(new BaseGraphRequestAdapter(authenticationProvider ?? new AnonymousAuthenticationProvider(), graphClientOptions, httpClient: httpClient),baseUrl)
{
}`

We're a 1p App, so the flow should be within each graph call, we'll include the bearer token issued by msGraph with the preauth permission we've requested.
Open to be reached out on Teams if that's easier for debugging.

**Comment by andrueastman** [comment]
@kyzhangZao 
Among your custom handlers, do you by any chance have customized compression handling? From the stack trace, it looks like the error is occurring due to the compression handler. Are you by any chance able to share how the HttpClient is configured as well?

**Comment by kyzhangZao** [comment]
Hi @andrueastman , No we have no customization of compression handling.  
```
var handlers = GraphClientFactory.CreateDefaultHandlers();
var redirectHandler = handlers.Single(handler => handler is RedirectHandler);
handlers.Remove(redirectHandler);
handlers.Add(new PollyHandler(this, traceableData));
```
These are the only modification we had on the handler.

**Comment by kyzhangZao** [comment]
The compression handler seems to be introduced in the sdk itself. I just tried, directly remove the compression handler within our service setup actually fixed this issue. But would like to check if this is something we should do/would there be any consequences if we remove this handler?

**Comment by andrueastman** [comment]
Hey @kyzhangZao,

Any chance you can confirm(or share a reference) if the `PollyHandler` is also trying to do some request compression/decompression or read the response content? If it does, it may mean that the error occurs due to it trying to be done twice by both handlers or the handler trying to read compressed content.

>  But would like to check if this is something we should do/would there be any consequences if we remove this handler?

Removing the `CompressionHandler` will result in the `AcceptEncoding` header not being sent so the API will not respond with compressed content. Therefore, you will lose the optimization but the SDK should still work.
