### ISSUE TITLE
No error factory registed when using GraphClient.RequestAdapter.SendAsync()

### ISSUE THREAD

**Issue by MichaMican** [microsoftgraph/msgraph-sdk-dotnet#2331]
We are using the RequestAdapter similarily to @andrueastman suggestion in #1689 to parse QueryParameters during runtime.
We are facing the issue that if we call the SendAsync function as outlined in #1689 we do not pass the errorMapping, hence when a error is thrown (for example a 404 because a device is not found) we receive the following error:
![Bild](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/45571948/aa8ea4a4-c692-4b48-b58f-1371170912a9)
```
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.Kiota.Abstractions.ApiException: The server returned an unexpected status code and no error factory is registered for this code: 404
         at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
         at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
         at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
```
Is there a way to get the default errorMapping to map the standard errors like 404, 400 etc. so i can pass it to the SendAsync function as a third parameter:
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/45571948/58c2d774-2f64-4566-bd4a-6f6e4e363427)

**For reference here an implementation example that causes this error:**
```cs
var requestInformation = _graphServiceClient.Devices["ec3c9948-d361-4efc-b654-44c562ee7a96"].ToGetRequestInformation(); // ec3c9948-d361-4efc-b654-44c562ee7a96 is a guid that does not exist in the tenant - Resulting in a 404 error
return await _graphServiceClient.RequestAdapter.SendAsync<Device>(requestInformation, Device.CreateFromDiscriminatorValue); // This now throws the error message outlined above instead of the standard parsed ODataError Exception
```

**Comment by andrueastman** [comment]
Thanks for raising this @MichaMican 

With the latest version of `Microsoft.Graph.Core` (v3.1.7) you should be able to pass to pass the errorMapping as below. 

```cs
var errorMapping = new Dictionary<string, ParsableFactory<IParsable>> 
{
    {"XXX", ODataError.CreateFromDiscriminatorValue},
};
await _graphServiceClient.RequestAdapter.SendAsync<Device>(requestInformation, Device.CreateFromDiscriminatorValue, errorMapping );
```

Earlier versions will need you to specify entries for 4XX and 5XX ranges

```cs
var errorMapping = new Dictionary<string, ParsableFactory<IParsable>> 
{
    {"4XX", ODataError.CreateFromDiscriminatorValue},
    {"5XX", ODataError.CreateFromDiscriminatorValue},
};
await _graphServiceClient.RequestAdapter.SendAsync<Device>(requestInformation, Device.CreateFromDiscriminatorValue, errorMapping );
```

**Comment by MichaMican** [comment]
We have tested this and it works like a charm! Thanks @andrueastman - absolute MVP!

We have implemented a Extension function to have easy access to this - this might be something you could consider adding to the out-of-the-box Graph SDK:

`Statics.cs`
```cs
using Microsoft.Graph.Models.ODataErrors;
using Microsoft.Kiota.Abstractions.Serialization;

public static class Statics
{
    public static Dictionary<string, ParsableFactory<IParsable>> GraphErrorMappings = new()
    {
        {"XXX", ODataError.CreateFromDiscriminatorValue }
    };
}
```

`Extensions.cs`
```cs
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

public static class Extensions 
{
    public static Task<T?> SendAsyncWithErrorMapping<T>(this IRequestAdapter requestAdapter, RequestInformation requestInformation, ParsableFactory<T> factory) where T : IParsable 
    {
        return requestAdapter.SendAsync<T>(requestInformation, factory, GraphErrorMapping.Mappings);
    }
}
```

(For this to work you need Graph core >= 3.1.7. For earlier versions the GraphErrorMaapings have to be changed as outlined by @andrueastman )

**Comment by MichaMican** [comment]
We have tested this and it works like a charm! Thanks @andrueastman - absolute MVP!

We have implemented a Extension function to have easy access to this - this might be something you could consider adding to the out-of-the-box Graph SDK:

`Statics.cs`
```cs
using Microsoft.Graph.Models.ODataErrors;
using Microsoft.Kiota.Abstractions.Serialization;

public static class Statics
{
    public static Dictionary<string, ParsableFactory<IParsable>> GraphErrorMappings = new()
    {
        {"XXX", ODataError.CreateFromDiscriminatorValue }
    };
}
```

`Extensions.cs`
```cs
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

public static class Extensions 
{
    public static Task<T?> SendAsyncWithErrorMapping<T>(this IRequestAdapter requestAdapter, RequestInformation requestInformation, ParsableFactory<T> factory) where T : IParsable 
    {
        return requestAdapter.SendAsync<T>(requestInformation, factory, GraphErrorMapping.Mappings);
    }
}
```

(For this to work you need Graph core >= 3.1.7. For earlier versions the GraphErrorMaapings have to be changed as outlined by @andrueastman )
