### ISSUE TITLE
AggregateException thrown when Service ins Unavailable

### ISSUE THREAD

**Issue by Danny4021** [microsoftgraph/msgraph-sdk-dotnet#2444]
### Describe the bug

Hello, 
when I make any kind of request to Graph (i.e. Send E-Mail, Get Delta, Get Folder, etc) I sometimes get an `AggregateException` from Kiota, when the Service is unavailable.

### Expected behavior

I wouldn't expect this to throw a `AggregateException` since this never happened before and it just started appearing randomly yesterday (haven't updated Graph since 10.04.2024).
I would expect this to be wrapped inside an `ApiError` .
Is this behaviour normal? Is this fixed in a newer version of the SDK? 

### How to reproduce

This just happens randomly when sending any kind of request to the Graph API (i.e. send mail, get mail, get folder, etc)
Her is an example request from me:
```csharp
await graphClient
					.Users[mailAddress]
					.Messages[mailId]
					.GetAsync()
```

### SDK Version

5.47.0

### Latest version known to work for scenario above?

<5.47.0

### Debug output

```
System.AggregateException: Too many retries performed. More than 3 retries encountered while sending the request. (HTTP request failed with status code: ServiceUnavailable.?
l?Qk?0????]???j???@???-n????N%I????Z??/?s??????S! ???r?g1?
--- End of inner exception stack trace ---
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.SendRetryAsync(HttpResponseMessage response, RetryHandlerOption retryOption, CancellationToken cancellationToken, ActivitySource activitySource)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.CompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims, Boolean isStreamResponse)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendNoContentAsync(RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Users.Item.SendMail.SendMailRequestBuilder.PostAsync(SendMailPostRequestBody body, Action`1 requestConfiguration, CancellationToken cancellationToken)
---> (Inner Exception #1) Microsoft.Kiota.Abstractions.ApiException: HTTP request failed with status code: ServiceUnavailable.?
l?Qk?0????]???j???@???-n????N%I????Z??/?s??????S! ???r?g1?
---> (Inner Exception #2) Microsoft.Kiota.Abstractions.ApiException: HTTP request failed with status code: ServiceUnavailable.?
l?Qk?0????]???j???@???-n????N%I????Z??/?s??????S! ???r?g1?
---> (Inner Exception #3) Microsoft.Kiota.Abstractions.ApiException: HTTP request failed with status code: ServiceUnavailable.?
l?Qk?0????]???j???@???-n????N%I????Z??/?s??????S! ???r?g1?
```

**Comment by andrueastman** [comment]
Thanks for raising this @Danny4021 

> This just happens randomly when sending any kind of request to the Graph API
This will occur in the event of transient errors in the API due to the returning of 429/502/503 response. In the event no transient errors occur in the API, you won't see these. 

We'll close this for now and track the consistency in errors via https://github.com/microsoft/kiota-http-dotnet/issues/244 so that this may be followed up from the library side.
