### ISSUE TITLE
User update throws with "AdditionalData can not be null" after migration from 5.47.0 to 5.51.0

### ISSUE THREAD

**Issue by faschwardalog** [microsoftgraph/msgraph-sdk-dotnet#2471]
### Describe the bug

I am trying to [update the settings](https://learn.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http) of a user. It was working fine up to now, but after the migration to 5.51.0 it crashes out with "AdditionalData can not be null". 

### Expected behavior

Users can be updated without the sdk crashing. Might relate to the user update endpoint not returning any body but just a 204.

### How to reproduce

Just try to update any user with version 5.51.0
```csharp
const string userId = "user-id";
var user = await _client.Users[userId].GetAsync(cancellationToken: cancellationToken);
user.City += "a";
await _client.Users[userId].PatchAsync(user, cancellationToken: cancellationToken);
```

### SDK Version

5.51.0

### Latest version known to work for scenario above?

5.47.0

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by DavidLievrouw** [comment]
Same here. Still works with v5.49.0. Here's my stacktrace:

```
System.AggregateException
One or more errors occurred. (AdditionalData can not be null) (Specified HTTP method is not allowed for the request target.)
  Exception doesn't have a stacktrace

System.InvalidOperationException
AdditionalData can not be null
   at Microsoft.Graph.Models.Entity.get_AdditionalData()
   at Microsoft.Graph.Models.Entity.Serialize(ISerializationWriter writer)
   at Microsoft.Graph.Models.DirectoryObject.Serialize(ISerializationWriter writer)
   at Microsoft.Graph.Models.Group.Serialize(ISerializationWriter writer)
   at Microsoft.Kiota.Serialization.Json.JsonSerializationWriter.WriteObjectValue[T](String key, T value, IParsable[] additionalValuesToMerge)
   at Microsoft.Kiota.Abstractions.RequestInformation.SetContentFromParsable[T](IRequestAdapter requestAdapter, String contentType, T item)
   at Microsoft.Graph.Groups.Item.GroupItemRequestBuilder.ToPatchRequestInformation(Group body, Action`1 requestConfiguration)
   at Microsoft.Graph.Groups.Item.GroupItemRequestBuilder.PatchAsync(Group body, Action`1 requestConfiguration, CancellationToken cancellationToken)
```

**Comment by TDroogers** [comment]
It can be fixed/hidden by adding a value to AdditionalData.

`fromGet.AdditionalData = new Dictionary<string, object>();`

**Comment by faschwardalog** [comment]
> It can be fixed/hidden by adding a value to AdditionalData.
> 
> `fromGet.AdditionalData = new Dictionary<string, object>();`

Unfortunately did not help me :-(
