### ISSUE TITLE
System.MissingMethodException : Method not found: 'System.Net.Http.HttpClient Microsoft.Kiota.Http.HttpClientLibrary.KiotaClientFactory.Create(System.Net.Http.HttpMessageHandler)'.

### ISSUE THREAD

**Issue by GabrielAPineiro** [microsoftgraph/msgraph-sdk-dotnet#2533]
### Describe the bug

I'm getting an error while trying to run some tests after updating version 1.4.3 of Microsoft.Kiota.Http.HttpClientLibrary. I looked into some issues and it said to update the Microsoft.Graph to the latest version, but I did and the error is still happening.

### Expected behavior

No error and method found

### How to reproduce

Create new GraphServiceClient() and use IAuthenticationProvider

### SDK Version

5.55.0

### Latest version known to work for scenario above?

Microsoft.Graph.5.52.0 Microsoft.Kiota.Abstractions.1.9.1 Microsoft.Kiota.Authentication.Azure.1.1.5 Microsoft.Kiota.Http.HttpClientLibrary.1.4.1 Microsoft.Kiota.Serialization.Form.1.2.0 Microsoft.Kiota.Serialization.Json.1.3.0 Microsoft.Kiota.Serialization.Multipart.1.1.4 Microsoft.Kiota.Serialization.Text.1.2.0

### Known Workarounds

Downgrading to:
Microsoft.Graph.5.52.0
Microsoft.Kiota.Abstractions.1.9.1
Microsoft.Kiota.Authentication.Azure.1.1.5
Microsoft.Kiota.Http.HttpClientLibrary.1.4.1
Microsoft.Kiota.Serialization.Form.1.2.0
Microsoft.Kiota.Serialization.Json.1.3.0
Microsoft.Kiota.Serialization.Multipart.1.1.4
Microsoft.Kiota.Serialization.Text.1.2.0

### Debug output

<details><summary>Click to expand log</summary>
```

System.MissingMethodException : Method not found: 'System.Net.Http.HttpClient Microsoft.Kiota.Http.HttpClientLibrary.KiotaClientFactory.Create(System.Net.Http.HttpMessageHandler)'.
   at Exclaimer.CrmIntegration.Client.ServiceCollectionExtensions.<>c.<AddCrmIntegration>b__1_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean hasDefaultValue, Object key)
   at lambda_method4(Closure, IServiceProvider, Object[])
   at Microsoft.Extensions.Http.DefaultTypedHttpClientFactory`1.CreateClient(HttpClient httpClient)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.AddTransientHelper[TClient,TImplementation](IServiceProvider s, IHttpClientBuilder builder)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass16_0`2.<AddTypedClientCore>b__0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at ExclaimerCloud.UI.Tests.ControllerTests.ControllersCanBeResolved(Type controllerType) in C:\Projects\exclaimercloud-ui\apps\cloud-ui\backend\ExclaimerCloud.UI.Tests\ControllerTests.cs:line 97
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)

```
</details>

### Other information

We are using .net8

**Comment by andrueastman** [comment]
Thanks for raising this @GabrielAPineiro 

Just to confirm do you have a reference to `Microsoft.Graph.Core`? Is this pointing to the latest version?

**Comment by GabrielAPineiro** [comment]
I'm not using Microsoft.Graph.Core directly, but the latest version from Microsoft.Graph is using it.
![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/104081429/ad1eb155-e90e-4df8-a294-ec03bf8c085e)

**Comment by andrueastman** [comment]
As `Microsoft.Graph.Core` already references `1.4.3 of Microsoft.Kiota.Http.HttpClientLibrary` do you still get the error if you remove all of the kiota dependencies from you project?

**Comment by GabrielAPineiro** [comment]
Not possible, our main project has dependencies in some projects that use Kiota for other things and don't use Graph. But I believe all the other projects have the latest reference from Kiota

**Comment by GabrielAPineiro** [comment]
Yeah you were right. One dependency went under our radar. Its working now

**Comment by andrueastman** [comment]
Thanks for confirming. Closing this one for now.

**Comment by joseEduardo-CG** [comment]
I have the same issue, what dependency did you have to install or update to fix it?

**Comment by andrueastman** [comment]
Any chance you can confirm this happens with the latest version? 

> Yeah you were right. One dependency went under our radar. Its working now

I believe, the issue here was that the project had a reference to an older dependency somewhere that wasn't aligned.
