### ISSUE TITLE
Issue with Enabling Phone Method for Azure AD B2C User via Graph API

### ISSUE THREAD

**Issue by Vijaykumarj** [microsoftgraph/msgraph-sdk-dotnet#2549]
### Describe the bug

I am currently working on enabling the phone method for Azure AD B2C users using the Graph API, specifically using the PhoneMethods for authentication. However, I am encountering an issue where the operation fails with the error message: "Cannot enable SMS sign-in on phone auth method as the credential policy is not enabled on user".

### Expected behavior

Phone method should be add to the user.

### How to reproduce

`if (adUser != null)
{
    var phoneMethods = graphClient.Users[adUser.Id].Authentication.PhoneMethods.GetAsync().Result;

    var requestBody = new PhoneAuthenticationMethod
    {
        PhoneNumber = "**********",
        PhoneType = AuthenticationPhoneType.Mobile,
        SmsSignInState = AuthenticationMethodSignInState.Ready
    };

    var phoneMethodsRes = graphClient.Users[adUser.Id].Authentication.PhoneMethods.PostAsync(requestBody).Result;

    if (phoneMethodsRes != null)
    {
        graphClient.Users[adUser.Id].Authentication.PhoneMethods[$"{phoneMethodsRes.Id}"].EnableSmsSignIn.PostAsync().Result;
    }

    var phoneMethodsLast = graphClient.Users[adUser.Id].Authentication.PhoneMethods.GetAsync().Result;
}
catch (Exception exp)
{
    Console.WriteLine($"Exception Caught: {exp.Message}");
}`

### SDK Version

5.56.0

### Debug output

<details><summary>Click to expand log</summary>
```

Microsoft.Graph.Models.ODataErrors.ODataError: Can not enable Sms sign in on phone auth method as the credential policy is not enabled on user.
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary`2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendNoContentAsync(RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendNoContentAsync(RequestInformation requestInfo, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Users.Item.Authentication.PhoneMethods.Item.EnableSmsSignIn.EnableSmsSignInRequestBuilder.PostAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
   at Program.Main(String[] args) in C:\Projects\GraphClient\Program.cs:line 76

```
</details>

### Configuration

- OS: Windows 11
-  .Net Core 6

![image](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/26544969/5c5c61c6-bb99-4c7a-a5aa-770a6b8d5278)
![image (1)](https://github.com/microsoftgraph/msgraph-sdk-dotnet/assets/26544969/4096a988-bd2a-4892-a5c9-42daaf028fd4)

**Comment by andrueastman** [comment]
Thanks for raising this @Vijaykumarj 

The error seems to suggest that the API is failing on the request due to the credential policy on the specific user. Any chance you can post the question at https://aka.ms/graphfeedback to get feedback from the API owners on what could be issue here?
