### ISSUE TITLE
InvalidRequest Error when using UploadSession to upload files to OneDrive

### ISSUE THREAD

**Issue by lavinir** [microsoftgraph/msgraph-sdk-dotnet#2599]
### Describe the bug

I am trying to upload files to the special App Folder in OneDrive. The code runs on multiple machines but some of them are getting errors attempting to upload files (each machine is using a different OneDrive account).

The Error being thrown is:

```
Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken) at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory1 factory, Dictionary2 errorMapping, CancellationToken cancellationToken) at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory1 factory, Dictionary2 errorMapping, CancellationToken cancellationToken) at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action1 requestConfiguration, CancellationToken cancellationToken)
```

No additional data indicating why the request is invalid or what might be causing the error.

### Expected behavior

The upload session is created successfully and file upload goes through. (Or an appropriate error message explaining what's wrong with the request comes back)

### How to reproduce

The code I am using to create the session:

```cs
var driveItem = await _userClient.Me.Drive.GetAsync();
            var appFolder = await _userClient.Drives[driveItem.Id].Special["approot"].GetAsync();

            var uploadSession = await _userClient.Drives[driveItem?.Id]
                .Items[appFolder.Id]
                .ItemWithPath(sanitizedDestinationFileName)
                .CreateUploadSession
                .PostAsync(new DriveUpload.CreateUploadSessionPostRequestBody()
                {
                    Item = new DriveItemUploadableProperties
                    {
                        Description = description
                    }
                });
```

### SDK Version

5.38.0

### Known Workarounds

None - Works in some instances and fails in others. 
The things that are different in each machine:
1. OneDrive Account
2. The Description in **DriveItemUploadableProperties**

### Debug output

<details><summary>Click to expand log</summary>
```
Error uploading backup: Microsoft.Graph.Models.ODataErrors.ODataError: Invalid request
at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.ThrowIfFailedResponse(HttpResponseMessage response, Dictionary2 errorMapping, Activity activityForAttributes, CancellationToken cancellationToken) at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory1 factory, Dictionary2 errorMapping, CancellationToken cancellationToken) at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory1 factory, Dictionary2 errorMapping, CancellationToken cancellationToken) at Microsoft.Graph.Drives.Item.Items.Item.CreateUploadSession.CreateUploadSessionRequestBuilder.PostAsync(CreateUploadSessionPostRequestBody body, Action1 requestConfiguration, CancellationToken cancellationToken)
```
</details>

### Configuration

Mix of architectures (x64, ARM64, ARM)

**Comment by andrueastman** [comment]
Thanks for raising this @lavinir 

Any chance you can share what is being done to sanitize the name in the `sanitizedDestinationFileName` variable? Do you perform any url encoding/decoding?

**Comment by lavinir** [comment]
Hi @andrueastman,

Sure, this just strips the suffix and then removes illegal chars from the string using this logic:

```cs
            if (string.IsNullOrEmpty(input))
            {
                return input; 
            }

            char[] illegalChars = { '*', ':', '<', '>', '?', '/', '\\', '|' };

            string sanitizedString = new string(input.Select(c => illegalChars.Contains(c) ? '_' : c).ToArray());

            return sanitizedString;
```

**Comment by andrueastman** [comment]
Thanks for the extra information here @lavinir 

Are you by any chance able to capture the filename in these scenarios? Ideally, the one drive API should be having the same naming restrictions to 

- https://support.microsoft.com/en-us/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa?ui=en-us&rs=en-us&ad=us#invalidcharacters
- https://learn.microsoft.com/en-us/onedrive/developer/rest-api/concepts/addressing-driveitems?view=odsp-graph-online#onedrive-reserved-characters

**Comment by lavinir** [comment]
Here is an example of a file name: "hass_backup_2024-08-05-12-57.tar" 
@andrueastman

**Comment by andrueastman** [comment]
Thanks for the extra information here @lavinir 
The file name here does not look to have an issue here. Any chance you can try to capture all the properties of error details by following the guidance at  https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/errors.md#handling-errors-in-the-microsoft-graph-net-client-library?

>Is it possible the Description could also impact this ?

Are you able to confirm if the description is very long or with special characters in this scenario?

**Comment by lavinir** [comment]
I apologize @andrueastman , Did not get this notification. No, the description should not have any special chars or be very long.
The guidance link above seems broken - getting a  404 on that link.
