### ISSUE TITLE
Incorrect NewtonSoft.Json reference in assembly

### ISSUE THREAD

**Issue by erwinvanhunen** [microsoftgraph/msgraph-sdk-dotnet#276]
Until recently the Microsoft.Graph.dll assembly references NewtonSoft.Json version 10.0.0.0.

However, when upgrading to the latest available nuget of the SDK (version 1.9.0) it the Graph assembly references NewtonSoft.Json version 6.0.0.0. The nuget package states however there is a reference to the NewtonSoft assembly starting at version 6.0.1 and younger than 12.0.0.0. This mismatch causes the Graph SDK to install succesfully if NewtonSoft 10.0.0.0 is available, but it fails at runtime due to the hard reference to 6.0.0.0.

error:

```
Get-PnPUnifiedGroup : Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral,
PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
```

stacktrace:

   at Microsoft.Graph.Serializer..ctor()
   at Microsoft.Graph.HttpProvider..ctor(HttpMessageHandler httpMessageHandler, Boolean disposeHandler, ISerializer serializer)
   at OfficeDevPnP.Core.Framework.Graph.PnPHttpProvider..ctor(Int32 retryCount, Int32 delay, String userAgent)
   at OfficeDevPnP.Core.Framework.Graph.UnifiedGroupsUtility.CreateGraphClient(String accessToken, Int32 retryCount, Int32 delay)
   at OfficeDevPnP.Core.Framework.Graph.UnifiedGroupsUtility.<>c__DisplayClass12_0.<<ListUnifiedGroups>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at OfficeDevPnP.Core.Framework.Graph.UnifiedGroupsUtility.ListUnifiedGroups(String accessToken, String displayName, String mailNickname, Int32 startIndex, Int32 endIndex, Boolean includeSite, Int32 retryCount, Int32 delay, Boolean includeClassification)
   at SharePointPnP.PowerShell.Commands.Graph.GetUnifiedGroup.ExecuteCmdlet()
   at SharePointPnP.PowerShell.Commands.Base.PnPGraphCmdlet.ProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by MIchaelMainer** [comment]
Ackknowledged. I'll respond with more info a bit later.

**Comment by erwinvanhunen** [comment]
As we're calling the assembly from a binary PowerShell module, we couldn't use the traditional assembly redirect method, we fixed it for now in our end by adding an assembly resolver in the appdomain that returns the correct (higher and available) version of the newtonsoft assembly when requested.

**Comment by MIchaelMainer** [comment]
From conversation with @jansenbe. Sharing here for other folks to find. 

We build the assembly with version 6 of NewtonSoft. This has been true for a while. I see what happened. 

NuGet version 1.3.0 used Newtonsoft.Json (>= 10.0.2)
NuGet version 1.7.0 used Newtonsoft.Json (>= 6.0.1 && < 11.0.0).
NuGet version 1.8.1 and 1.9.0 use Newtonsoft.Json (>= 6.0.1 && < 12.0.0)  

OfficeDevPnP.Core last took a dependency on Microsoft.Graph 1.3 which we mistakenly made the Newtonsoft.Json (>= 10.0.2) dependency. This was an error as it excluded the use of this library in projects with preexisting dependencies on earlier versions of Newtonsoft.Json. This would have forced customers to upgrade to later versions.

We build with an earlier version so that a customer with an existing project and an existing reference to Newtonsoft.Json can use the .Net client library. You need to add an assembly binding redirect. I haven’t tried to do this myself yet (I probably should so that I can understand it better). 

[Add an assembly binding redirect](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions) to address this.

And in case of PowerShell, here's how a [PowerShell binding redirect](https://gist.github.com/JamesRandall/444f3365751edb130bef197f2222cfa5) can be done.
