### ISSUE TITLE
Json.Net doesn't serialize DriveItem content

### ISSUE THREAD

**Issue by bakester14** [microsoftgraph/msgraph-sdk-dotnet#507]
Json.Net used to be able to serialize streams directly, now it needs a "JsonTextWriter" which I don't think this SDK has accounted for yet. Will dig through the code to confirm that shortly. See: https://stackoverflow.com/questions/8157636/can-json-net-serialize-deserialize-to-from-a-stream for old vs new behavior

### Expected behavior
https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/api/driveitem-put-content.md (note - documentation outdated, using old `PutAsync` method instead of new `UpdateAsync` method)

Additionally: https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/218 showing the last comments made on this endpoint, similar but different complaint that had a workaround at that time

### Actual behavior

I get the following error trying to upload content via this endpoint in the 1.15 and 1.16 versions of this SDK: 

```
Newtonsoft.Json.JsonSerializationException: Error getting value from 'ReadTimeout' on 'System.IO.MemoryStream'. ---> System.InvalidOperationException: Timeouts are not supported on this stream.
   at System.IO.Stream.get_ReadTimeout()
   at lambda_method(Closure , Object )
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   at Microsoft.Graph.Serializer.SerializeObject(Object serializeableObject)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.DriveItemRequest.UpdateAsync(DriveItem driveItemToUpdate, CancellationToken cancellationToken)
```

### Steps to reproduce the behavior

You can hit this error with the following snippet of code (inside an appropriate program with a properly authenticated GraphServiceClient):

```
var graph = new GraphServiceClient(new Authorizer()); // however you auth

byte[] contentBytes = new byte[1]{Convert.ToByte('a')};
using (var mStream = new MemoryStream(contentBytes))
{
	var uploadItem = new DriveItem
	{
		Content = mStream
	};

	graph.Me.Drive.Items["<Guid of existing, owned drive item>"]
		.Request()
		.UpdateAsync(uploadItem)
		.Wait();
}
```

**Comment by bakester14** [comment]
I should include that I haven't installed anything but the included version of Newtonsoft.Json, which for me (.Net Core might change this idk) is 9.0.1

**Comment by MIchaelMainer** [comment]
> 	graph.Me.Drive.Items["<Guid of existing, owned drive item>"]
		.Request()
		.UpdateAsync(uploadItem)

This call is to update the metadata on the item. See [Update DriveItem properties](https://docs.microsoft.com/en-us/graph/api/driveitem-update?view=graph-rest-1.0&tabs=http). 

While DriveItem.Content is Stream, that isn't how the contents of a DriveItem are updated.
https://docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&tabs=http

The call should be 

```csharp
using (var mStream = new MemoryStream(contentBytes))
{
	graph.Me.Drive.Items["<Guid of existing, owned drive item>"]
		.Request()
		.PutAsync(mStream)
		.Wait();
}
```

What you described is what would be intuitively expected. We partially generate the client library from metadata so some API forms are not what is expected.

**Comment by bakester14** [comment]
@MIchaelMainer 

Looking at src/Microsoft.Graph/Requests/Generated/DriveItemRequest.cs, I don't see a PutAsync. My IDE can't find that definition either. Are you positive that that is the right method to call to update the content of a DriveItem?

**Comment by MIchaelMainer** [comment]
@bakester14 You're correct. I forgot the Content property.

```csharp
using (var mStream = new MemoryStream(contentBytes))
{
	graph.Me.Drive.Items["<Guid of existing, owned drive item>"]
		.Content
		.Request()
		.PutAsync(mStream)
		.Wait();
}
```
