### ISSUE TITLE
Found a function 'microsoft.graph.answer' on an open property

### ISSUE THREAD

**Issue by wimvanhouts** [microsoftgraph/msgraph-sdk-dotnet#625]
When I receive a comms notificaton for a new call to my web api, I want to answer this call using the call answer function of the Graph API. The request fails with a bad request result and following lines:

```
System.AggregateException: One or more errors occurred. (Code: BadRequest
Message: Found a function 'microsoft.graph.answer' on an open property. Functions on open properties are not supported.
Inner error:
        AdditionalData:
        request-id: 8e0e59d2-b63c-425d-a58f-3e1ec73b0204
        date: 2020-01-30T11:53:11
ClientRequestId: 8e0e59d2-b63c-425d-a58f-3e1ec73b0204
)
 ---> Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: BadRequest
Message: Found a function 'microsoft.graph.answer' on an open property. Functions on open properties are not supported.
Inner error:
        AdditionalData:
        request-id: 8e0e59d2-b63c-425d-a58f-3e1ec73b0204
        date: 2020-01-30T11:53:11
ClientRequestId: 8e0e59d2-b63c-425d-a58f-3e1ec73b0204

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at XQi_Engine.Modules.Standard.MsGraph.MsGraphWorkerActor.HandleAnswerCall(MsGraphAnswerCall m) in C:\XQTING\Repos\App - XQi Engine\XQi Engine\XQi Engine\Modules\Standard\MsGraph\MsGraphWorkerActor.cs:line 43
```
1. create a bot registration that can handle calls
2. in the handler of the comms notification, fetch the call ID
3. execute following code with this call ID
```C#
var graphClient = new GraphServiceClient(_authentication);

var mediaConfig = new ServiceHostedMediaConfig();

var acceptedModalities = new List<Modality>()
{
    Modality.Audio
};

try
{
    graphClient.Communications.Calls[m.CallId].Answer(m.CallbackUri, mediaConfig, acceptedModalities).Request().PostAsync().Wait();
}
catch(Exception ex)
{
    _log.Error(ex, "Exception while answering call");
}
```
The code above is as good as similar to the code in the reference documentation, so I assume this should work.

Remark: I get this error using the .NET SDK, but, I also tried with the Java SDK and didn't see the same behaviour. Therefore I post it in the .NET SDK repository.
Question: What does the error actually mean, there is very little or no information available on this, not even SO
Question: Is there something in Azure or O365 where I can find more information when I have the request id mentioned in the exception?

**Comment by wimvanhouts** [comment]
Ok, solved the issue. Partially a mea culpa here... turns out I was using a bogus call ID. Unfortunatly, the returned result didn't give any indication and thus left me clueless and looking in other directions.
