### ISSUE TITLE
User RevokeSignInSessions does not handle proper response type

### ISSUE THREAD

**Issue by kensykora** [microsoftgraph/msgraph-sdk-dotnet#710]
**Describe the bug**
I'm trying to invoke this endpoint here: https://docs.microsoft.com/en-us/graph/api/user-revokesigninsessions?view=graph-rest-1.0&tabs=http

It describes it as 

```
POST /users/{id | userPrincipalName}/revokeSignInSessions
```

I'm invoking the c# client lib as such:

```csharp
public async Task RevokeSignInSessions(Guid id)
        {
            await _graphClient.Users[id.ToString()]
                .RevokeSignInSessions()
                .Request()
                .PostAsync();
        }
```

However, this throws an error:

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadAsBoolean()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Graph.Serializer.DeserializeObject[T](String inputString)
   at Microsoft.Graph.ResponseHandler.HandleResponse[T](HttpResponseMessage response)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at UserManagement.Core.Concretes.AdGraphService.RevokeSignInSessions(Guid id)
```

**To Reproduce**
1. Run code snippet as described above

*Expected*: Task continues without error if the operation is successful.
*Actual*: Refresh tokens are revoked, but SDK throws the above exception.

**Screenshots**

**Additional context**
NuGet version 

Microsoft.Graph v3.6.0
Microsoft.Graph.Auth v1.0.0-preview.4

**Comment by MIchaelMainer** [comment]
This is caused by an error in the service API response.
https://docs.microsoft.com/en-us/graph/known-issues#revoke-sign-in-sessions-returns-wrong-http-code. It is returning an unexpected 

The metadata states this:

      <Action Name="revokeSignInSessions" IsBound="true">
        <Parameter Name="bindingParameter" Type="graph.user" Nullable="false" />
        <ReturnType Type="Edm.Boolean" />
      </Action>

This is a generator issue.
