### ISSUE TITLE
Method Not Found - System.Threading.Tasks.Task

### ISSUE THREAD

**Issue by Verthosa** [microsoftgraph/msgraph-sdk-dotnet#713]
Hello, i don't think this might be an issue with the nuget package but did anyone have an issue having following error: 
**Method not found: 'System.Threading.Tasks.Task`1<!!0>**

```
 at Microsoft.Graph.DriveRequest.<GetAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Graph.DriveRequest.GetAsync(CancellationToken cancellationToken)
   at Microsoft.Graph.DriveRequest.GetAsync()
   at BizzMine.Data.Repositories.OnlineEditorRepo.OnlineEditorRepository.<RequestSuccess>d__10.MoveNext() in C:\Users\geertverthe\Documents\repos\bizzmine\BizzMine.Data.Repositories\OnlineEditorRepo\OnlineEditorRepository.cs:line 89
```

I'm using following code to interact with my OneDrive, using a valid Access Token 
`Drive myDrive = await _graphServiceClient.Me.Drive.Request().GetAsync();`

I am using .net 4.6.1. It looks like some interference with other nuget packages and might be fixed using binding redirection. 

Can anyone shed a light on this please? Would be greatly appreciated

**Comment by Verthosa** [comment]
Nevermind, i was able to resolve this: 

_Since our solution and projects contain lots of nuget packages, one of them was system.net.http. Apparantly this came with a package NETStandard.Library.1.6.1. 
I found it strange to have a nuget package for system.net.http as this is just in the framework itself. 

I could delete the system.net.http nuget packages after upgrading NETSTandard.Library.1.6.1 to the latest version. 

Only changes i had to do was referencing the FRAMEWORK system.net.http in projects where it was missing and removing an obsolete binding redirect in some projects.

It works fine now :-)_
