### ISSUE TITLE
[Client bug]: Unable to retrieve Stream from Batch request result

### ISSUE THREAD

**Issue by fonbrauzen** [microsoftgraph/msgraph-sdk-dotnet#728]
**Describe the bug**
Hi,

```
var requestUserPhotoFile = client.Users["{My_User_Id}"].Photo.Content.Request();
var resultUserPhotoFile2 = requestUserPhotoFile.GetAsync().Result;  // correct stream answer
var batchRequestContent = new BatchRequestContent();
var userPhotoFileRequestId = batchRequestContent.AddBatchRequestStep(requestUserPhotoFile);
BatchResponseContent batchResponse = client.Batch.Request().PostAsync(batchRequestContent).Result;
var responseUserPhotoFile = batchResponse.GetResponseByIdAsync<Stream>(userPhotoFileRequestId).Result;
```
Exception:

Unhandled exception. System.AggregateException: One or more errors occurred. (Error parsing comment. Expected: *, got 9. Path '', line 1, position 1.)
---> Newtonsoft.Json.JsonReaderException: Error parsing comment. Expected: *, got 9. Path '', line 1, position 1.
at Newtonsoft.Json.JsonTextReader.ParseComment(Boolean setToken)
at Newtonsoft.Json.JsonTextReader.ParseValue()
at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at Microsoft.Graph.ResponseHandler.HandleResponse[T](HttpResponseMessage response)

I guess the body incorrectly interpreted as a JSON, Graph for .NET Core 3.8.0
Am I doing it wrong, or the only workaround just not use batch for this case?

Also not working:

```
var response = batchResponse.GetResponseByIdAsync(userPhotoFileRequestId).Result;
var resultUserPhotoFile = response.Content.ReadAsStreamAsync().Result;
```

**To Reproduce**
1. with .net Graph SDK 3.8.0 NuGet try to get your user photo content
2. without batch => correct stream
3. with batch => stream couldn't be retrieved

**Expected behavior**
correct Stream object returning in .GetResponseByIdAsync<Stream>

**Client version**
3.8.0 Graph NuGet package.

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - .NET Core 3.1
 
[AB#7246](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7246)

**Comment by MIchaelMainer** [comment]
@andrueastman , can you investigate this and find out what the content looks like when a stream response is requested via batch. This isn't expected to work but I'd like to see why.

**Comment by andrueastman** [comment]
Sure thing. I will look into this.

**Comment by andrueastman** [comment]
This is now resolved via https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/262 and available through https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.7

The request stream in a batch content should now be accessible by using the new method below.

```cs
using var responseStream = await batchResponseContent.GetResponseStreamByIdAsync("1");
```
