### ISSUE TITLE
[BETA] A type named 'microsoft.substrateConnectors.externalConnection' could not be resolved by the model.

### ISSUE THREAD

**Issue by mhomol** [microsoftgraph/msgraph-sdk-dotnet#746]
**Describe the bug**
I am using the latest Beta version of Microsoft Graph SDK.  I have a working GraphServiceClient that is working with the new ExternalConnection objects.  From my console app, I am able to perform both GetAsync and DeleteAsync just fine, however AddAsync throws the following error: 

A type named 'microsoft.substrateConnectors.externalConnection' could not be resolved by the model.

I have basically used the example provided by the beta documentation.

**To Reproduce**
1. From terminal run:
```bash
dotnet new console -o HomolCrawl
```
2. From terminal run:
```bash
cd HomolCrawl
dotnet add package Microsoft.Identity.Client
dotnet add package Microsoft.Graph.Beta -v 0.19.0-preview
dotnet add package Microsoft.Graph.Auth -v 1.0.0-preview.5
dotnet add package Microsoft.Extensions.Configuration
dotnet add package Microsoft.Extensions.Configuration.FileExtensions
dotnet add package Microsoft.Extensions.Configuration.Json
```
3. Open `Program.cs` and replace the entire code block with this: 

```csharp
using System;
using Microsoft.Identity.Client;
using System.Collections.Generic;
using System.IO;
using System.Security;
using System.Threading.Tasks;
using Microsoft.Graph;
using Microsoft.Graph.Auth;
using Microsoft.Extensions.Configuration;

namespace HomolCrawl
{
    class Program
    {
        enum Action
        {
            Add,
            Get,
            Update,
            Delete
        }

        static async Task Main(string[] args)
        {
            try
            {
                if (args.Length == 0)
                {
                    Console.WriteLine("Need a command...");
                    return;
                }

                Action action;
                if (!Enum.TryParse(args[0], true, out action))
                {
                    Console.WriteLine("An action must be specified.");
                    return;
                }

                var config = LoadAppSettings();
                if (config == null)
                {
                    Console.WriteLine("Invalid appsettings.json file.");
                    return;
                }

                var client = GetAuthenticatedGraphClient(config);

                switch (action)
                {
                    case Action.Add:
                        Console.WriteLine("ID:");
                        string newid = Console.ReadLine();
                        Console.WriteLine("Name:");
                        string newname = Console.ReadLine();
                        Console.WriteLine("Description:");
                        string newdesc = Console.ReadLine();
                        var externalConnection = new Microsoft.Graph.ExternalConnection
                        {
                            Id = newid,
                            Name = newname,
                            Description = newdesc
                        };

                        await client.External.Connections
                            .Request()
                            .AddAsync(externalConnection);
                        break;
                    case Action.Get:
                        Console.WriteLine("Fetching Connections...");

                        var connections = await client.External.Connections
                            .Request()
                            .GetAsync();

                        foreach (var conn in connections)
                        {
                            Console.WriteLine($"{conn.Id}: {conn.Name}");
                        }
                        break;
                    case Action.Update:
                        Console.WriteLine("Coming Soon...");
                        break;
                    case Action.Delete:
                        Console.WriteLine("What connection ID do you want to delete?");
                        string id = Console.ReadLine();

                        Console.WriteLine($"Are you sure you want to delete {id}? (y/N)");
                        string confirm = Console.ReadLine();

                        if (confirm == "y" || confirm == "yes")
                        {
                            await client.External.Connections[id]
                                .Request()
                                .DeleteAsync();

                            Console.WriteLine($"Successfully deleted connection {id}");
                        }
                        else
                        {
                            Console.WriteLine("Nothing happened.");
                        }
                        break;
                    default:
                        Console.WriteLine("No action identified.  Nothing happened.");
                        break;
                }
            }
            catch (System.Exception ex)
            {
                Console.WriteLine("Error occurred:");
                Console.WriteLine(ex.ToString());
                return;
            }
        }

        private static IConfigurationRoot LoadAppSettings()
        {
            try
            {
                var config = new ConfigurationBuilder()
                                  .SetBasePath(System.IO.Directory.GetCurrentDirectory())
                                  .AddJsonFile("appsettings.json", false, true)
                                  .Build();

                if (string.IsNullOrEmpty(config["applicationId"]) ||
                    string.IsNullOrEmpty(config["tenantId"]) ||
                    string.IsNullOrEmpty(config["secret"]))
                {
                    return null;
                }

                return config;
            }
            catch (System.IO.FileNotFoundException)
            {
                return null;
            }
        }

        private static ClientCredentialProvider CreateAuthorizationProvider(IConfigurationRoot config)
        {
            var clientId = config["applicationId"];
            var authority = $"https://login.microsoftonline.com/{config["tenantId"]}/v2.0";
            var tenantID = config["tenantId"];
            var clientSecret = config["secret"];

            List<string> scopes = new List<string>();
            scopes.Add("User.Read");
            scopes.Add("ExternalItem.ReadWrite.All");

            IConfidentialClientApplication confidentialClientApplication = ConfidentialClientApplicationBuilder
                .Create(clientId)
                .WithTenantId(tenantID)
                .WithClientSecret(clientSecret)
                .Build();

            ClientCredentialProvider authProvider = new ClientCredentialProvider(confidentialClientApplication);

            return authProvider;

            //return MsalAuthenticationProvider.GetInstance(cca, scopes.ToArray(), tenantID, clientId, clientSecret);
        }

        private static GraphServiceClient GetAuthenticatedGraphClient(IConfigurationRoot config)
        {
            var authenticationProvider = CreateAuthorizationProvider(config);
            var graphClient = new GraphServiceClient(authenticationProvider);
            return graphClient;
        }
    }
}
```
4. Create an `appsettings.json` file in the root directory.
5. Put the following into your `appsettings.json` file:
```json
{
  "tenantId": "[YOUR TENANT ID]",
  "applicationId": "[YOUR APP ID]",
  "secret": "[YOUR SECRET]"
}
```
6. From your terminal, run `dotnet build`
7. From your terminal, run `dotnet run get` to see that your client credential token is working fine, like mine was.
8. From your terminal run `dotnet run add` and fill in the 3 prompts.
9. See error

```bash
Error occurred:
Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: InvalidRequest
Message: The request is malformed or incorrect.
Inner error:
        Code: DeserializationError
Message: A type named 'microsoft.substrateConnectors.externalConnection' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.
AdditionalData:
        date: 2020-07-22T17:53:15
        request-id: e445fc12-9047-4730-bd77-5b794e1ceb37
ClientRequestId: e445fc12-9047-4730-bd77-5b794e1ceb37

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at HomolCrawl.Program.Main(String[] args) in /Users/mikehomol/Development/Company Work/TW/Projects/cci/Search/Graph-Connectors/Custom-Connector/HomolCrawl/Program.cs:line 65
```

**Expected behavior**
Expected it to add an External Connection using the 3 properties entered.  

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - .Net Core 3.1

**Additional context**
> _NOTE_ that I *was* able to add an external connection using the REST API only - I got a valid client credential bearer token then performed a POST to `https://graph.microsoft.com/beta/external/connections` with a payload like this:
```json
{
  "id": "WorkingExample",
  "name": "Working Example",
  "description": "This one worked from the REST API only, NOT the SDK."
}
```

**Comment by mhomol** [comment]
I figured out the issue by reading through the sample graph connector code.  I only figured it out by reading the comments in the code though.  Essentially ODataType has to be set to null in the new ExternalConnection.

```csharp
                        var externalConnection = new Microsoft.Graph.ExternalConnection
                        {
                            ODataType = null,
                            Id = newid,
                            Name = newname,
                            Description = newdesc
                        };
```

The same is true for creating the Schema for a property as well.  So one of 2 things is true: either this is a bug in the code or, if it is always intended, then you need to update the documentation for both externalItem and schema creation to denote this rule.
