### ISSUE TITLE
System.NotSupportedException: The collection type 'Microsoft.Graph.IUserAppRoleAssignmentsCollectionPage' on 'Microsoft.Graph.User.AppRoleAssignments' is not supported.

### ISSUE THREAD

**Issue by eman-calma** [microsoftgraph/msgraph-sdk-dotnet#820]
I am getting this error whenever I create a user using the microsoft graph client library. What does this mean? 
[AB#7226](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7226)

**Comment by MIchaelMainer** [comment]
@eman-calma Please share with me the code you used when you got this.

**Comment by eman-calma** [comment]
Hi @MIchaelMainer ,

Here is my code.

try
        {
          var oUser = new Microsoft.Graph.User()
          {
            AccountEnabled = true, //True by default
            DisplayName = request.EmailAddress,
            GivenName = request.FirstName,
            Surname = request.LastName,
            UserPrincipalName = request.EmailAddress,
            MailNickname = "Unknown",
            MobilePhone = request.MobileNumber.FormatPhoneNumber(),
            PostalCode = request.PostCode,
            PasswordProfile = new PasswordProfile() { ForceChangePasswordNextSignIn = true, Password = _configuration["AppSettings:UserDefaultPWD"] }

          };

          //User custom attributes
          IDictionary<string, object> extensionInstance = new Dictionary<string, object>();
          extensionInstance.Add(_extension_{appid}_{customfield1}, request.{customfield1});
          oUser.AdditionalData = extensionInstance;

          var client = _graphClient.Connect();
          var user = await client.Users.Request().AddAsync(oUser);

          return new ResponseModel() { Success = true, Message = "User successfully added.", Data = user };
        }
        catch (Exception ex)
        {
          return ResponseModel.Failed($"An exception was thrown while creating the user.{Environment.NewLine}{ex.FormatMessage()}");
        }


This code was working before without any error. Although the user is created properly in Azure AD, but I am getting that error response.

**Comment by MIchaelMainer** [comment]
Strange. Can you share a sanitized view of the response body? Is appRoleAssignments set on the item in the response? I can't repro this.

**Comment by eman-calma** [comment]
Here is the exact response that I am getting. Please do note that the user is created successfully in Azure AD, and even when I am debugging the code it does not get any error.

`System.NotSupportedException: The collection type 'Microsoft.Graph.IUserAppRoleAssignmentsCollectionPage' on 'Microsoft.Graph.User.AppRoleAssignments' is not supported.
   at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type classType)
   at System.Text.Json.JsonPropertyInfo.get_RuntimeClassInfo()
   at System.Text.Json.JsonSerializer.Write(Utf8JsonWriter writer, Int32 originalWriterDepth, Int32 flushThreshold, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteAsyncCore(Stream utf8Json, Object value, Type inputType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 374
Content-Type: application/json
Host: localhost:44354
User-Agent: PostmanRuntime/7.26.5
Postman-Token: c21bbeab-ea75-4fb2-a23c-3494b33a17b0`

**Comment by MIchaelMainer** [comment]
It looks like you are using this library with the 2.0 preview of Microsoft.Graph.Core. Use the 1.x version and let me know if that works.

**Comment by eman-calma** [comment]
I'm using version 3.17 and tried updating with the latest SKD that reference to Microsoft.Graph.Core 1.22 today but still same error exist.

![image](https://user-images.githubusercontent.com/25030981/96254749-85c19480-1001-11eb-9329-2c432fcdacf8.png)

**Comment by andrueastman** [comment]
@eman-calma Any chance you resolved this?

**Comment by udlose** [comment]
My guess is it is related to the fact that they don't support the `System.Text.Json` serializer yet - see here and please upvote that Issue to get them to fix it!

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/791

**Comment by MIchaelMainer** [comment]
Please try out the preview update that uses `System.Text.Json`. Give us feedback in this issue.

https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935

**Comment by udlose** [comment]
@eman-calma @andrueastman - it looks like they've finally released support for `System.Text.Json` here - https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/935

**Comment by andrueastman** [comment]
@eman-calma Closing due to inactivity. Please reopen if you are still experiencing this issue.
