### ISSUE TITLE
UnknownError during request to Microsoft.Graph API  while updating subscription.

### ISSUE THREAD

**Issue by Yury3cx** [microsoftgraph/msgraph-sdk-dotnet#828]
**Describe the bug**
Following code produces sometime "UnknownError":

                   await _client.Subscriptions[subscription.Id].Request().UpdateAsync(new Subscription()
                    {
                        ExpirationDateTime = now.Add(SubscriptionExpirationTime),
                    }, token);

**To Reproduce**
Reproduced for 70% of cases.

**Expected behavior**
Request will return expected result.

**Screenshots**
We get following error: 
2020/08/25 05:00:31.629|26499|0049|Erro|Error running Office365 synchronization: Code: UnknownError
Inner error:
    AdditionalData:
    date: 2020-08-25T03:00:31
    request-id: b91dfe7d-3ed8-454e-b5ca-88ad02210943
ClientRequestId: b91dfe7d-3ed8-454e-b5ca-88ad02210943

2020/08/25 05:00:31.810|26499|0049|Erro|FullStackTrace: at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.GraphServiceSubscriptionsCollectionRequest.GetAsync(CancellationToken cancellationToken)
   at Integration.Office365.Notifications.Office365SubscriptionManager.GetSubscriptionsAsync(CancellationToken token)
   at Integration.Office365.Synchronization.Office365SyncExecutor.ExecuteFullSynchronizationAsync(License license, Office365Configuration configuration, CancellationToken token)

**Desktop (please complete the following information):**
Not applicable

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
This code was fully functional more than 2 two years, but approximately 1 month ago a lot of our customers begin to complain.

**Comment by MIchaelMainer** [comment]
@Yury3cx Do you have a requestId and date from an exception that has occurred more recently?

**Comment by Yury3cx** [comment]
@MIchaelMainer Here is the latest we have:

2020/10/26 05:00:30.886|25504|0031|Erro|Error running Office365 synchronization: Code: UnknownError
Inner error:
    AdditionalData:
    date: 2020-10-26T04:01:14
    request-id: 060c022f-543b-45a1-83ee-2d5e2f57dcfc
    client-request-id: 060c022f-543b-45a1-83ee-2d5e2f57dcfc
ClientRequestId: 060c022f-543b-45a1-83ee-2d5e2f57dcfc

2020/10/26 05:00:30.888|25504|0031|Erro|FullStackTrace: at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.GraphServiceSubscriptionsCollectionRequest.GetAsync(CancellationToken cancellationToken)
   at Integration.Office365.Notifications.Office365SubscriptionManager.GetSubscriptionsAsync(CancellationToken token)
   at Integration.Office365.Synchronization.Office365SyncExecutor.ExecuteFullSynchronizationAsync(License license, Office365Configuration configuration, CancellationToken token)

**Comment by MIchaelMainer** [comment]
Thank you for the follow up information. This is an issue on the service -- I've opened an incident to track this. 211377488
