### ISSUE TITLE
Access Denied error for OneDrive for Business account

### ISSUE THREAD

**Issue by andy61i** [microsoftgraph/msgraph-sdk-dotnet#922]
The following code gives the Access Denied error for a OneDrive for Business account on Windows 10:
`DriveItem item = _client.Drive.Special.AppRoot.ItemWithPath(PATH_TO_FILE).Request().Select("name,id,lastModifiedDateTime,file").GetAsync().Result;`

However this code works just fine for personal OneDrive accounts. Furthermore, the similar code works perfectly for the this exactly business account on other operating systems (via appropriate MSGraph libs): Android, macOS, iOS.

The error dump:

EXCEPTION: SafeInCloud.Models.SyncException ---> System.AggregateException: One or more errors occurred. ---> Microsoft.Graph.ServiceException: Code: accessDenied
Message: Access denied
Inner error:
	AdditionalData:
	date: 2021-03-04T11:10:29
	request-id: aefd5499-cbf0-45c1-8ab6-ffa37d1899d7
	client-request-id: aefd5499-cbf0-45c1-8ab6-ffa37d1899d7
ClientRequestId: aefd5499-cbf0-45c1-8ab6-ffa37d1899d7

   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.DriveItemRequest.<GetAsync>d__6.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at SafeInCloud.MsGraph.MsGraphDriver.GetFileRevision(String fileName) in C:\Users\andy\projects\sic_windows\SafeInCloud\MsGraph\MsGraphDriver.cs:line 200
   --- End of inner exception stack trace ---
   at SafeInCloud.Models.Cloud.HandleException(SyncException se) in C:\Users\andy\projects\sic_windows\SafeInCloud\Models\Cloud.cs:line 351
   at SafeInCloud.Models.Cloud.GetFileRevision(String fileName) in C:\Users\andy\projects\sic_windows\SafeInCloud\Models\Cloud.cs:line 289
   at SafeInCloud.Models.DatabaseSynchronizer.SyncDatabase(ProtectedString cloudPassword) in C:\Users\andy\projects\sic_windows\SafeInCloud\Models\DatabaseSynchronizer.cs:line 85
   at SafeInCloud.Models.SyncModel.TwoWaySyncTask.Sync() in C:\Users\andy\projects\sic_windows\SafeInCloud\Models\SyncModel.cs:line 85
   at SafeInCloud.Models.SyncModel.SyncTask.Run() in C:\Users\andy\projects\sic_windows\SafeInCloud\Models\SyncModel.cs:line 52

The requested scopes:
`"openid",
"offline_access",
"profile",
"User.ReadBasic.All",
"Files.ReadWrite.AppFolder",
"Files.ReadWrite"`

Versions:
`Microsoft.Graph 3.26.0,
Microsoft.Graph.Core 1.24.0,
Microsoft.Identity.Client 4.27.0,
Windows 10 Pro v2004 build 19041.804`
 
[AB#8440](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8440)

**Comment by andy61i** [comment]
Sorry, the problem was in missing "Me"

_client.Drive. -> _client.Me.Drive.
