### ISSUE TITLE
Intermittent NullReferenceException from Getting User Information from GraphServiceClient

### ISSUE THREAD

**Issue by amartinrelativity** [microsoftgraph/msgraph-sdk-dotnet#934]
Using version:
v3.23.0 of Microsoft.Graph
v1.24.0 of Microsoft.Graph.Core

Making this call ServiceClient.Users["{EmailAddress}"].Request().GetAsync()

is throwing the following error:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.UserRequest.GetAsync(CancellationToken cancellationToken)`

We are having trouble reproducing this and only seeing it occasionally. Is there a fix available? 
[AB#8662](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8662)

**Comment by andrueastman** [comment]
@amartinrelativity 
Thanks for opening this issue. 
We actually closed a similar issue [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/901) recently. 
Are you able to to help out with more information on the nature of the response? Are you able to determine if the response status code is a 200 or a non success status code?

**Comment by amartinrelativity** [comment]
Unfortunately we're only seeing the error in a closed production environment, so I can't manually watch the traffic. My assumption is we're getting a 200, as the e-mail address being used is valid.

**Comment by andrueastman** [comment]
@amartinrelativity Any chance you could try following the guide [here on logging requests](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/dev/docs/logging-requests.md). This will help us figure out if its indeed a 200?

**Comment by SDolha** [comment]
I've recently begin to see a very similar issue occurring every time when we add task.Assignments; it worked well some time ago:

```
var task = new PlannerTask { Assignments = new PlannerAssignments() };
foreach (var userId in addedUserIds)
    task.Assignments.AddAssignee(userId);
task = await graphClient.Planner.Tasks[id].Request()
    .Header("If-Match", etag)
    .Header("prefer", "return=representation")
    .UpdateAsync(task);
```

We get:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.PlannerTaskRequest.UpdateAsync(PlannerTask plannerTaskToUpdate, CancellationToken cancellationToken)

**Comment by andrueastman** [comment]
@SDolha Thanks for raising the issue. Are you able to capture a fiddler trace to get back response information of the response (status code and example response)? Also, can you provide information of which version of the SDK you are using?

**Comment by SDolha** [comment]
I've seen the issue above with code leveraging version 3.8.0 of the SDK. Now I've updated to 3.29.0 and the error received seems changed to a bit better - digging it at the moment:

```
Status Code: BadRequest
Microsoft.Graph.ServiceException: Message: The request is invalid:
A type named 'microsoft.taskServices.plannerAssignmentCollection' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.
[...]

   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.PlannerTaskRequest.UpdateAsync(PlannerTask plannerTaskToUpdate, CancellationToken cancellationToken)
...
```

**Comment by SDolha** [comment]
I've solved the issue following the advice from here: https://github.com/nicolonsky/ModernWorkplaceConcierge/issues/75
It's strange that the SDK requires me to force setting ODataType to null, but it seems to be a valid workaround, at least for now:

```
Assignments = new PlannerAssignments { ODataType = null }
```

**Comment by djswilly** [comment]
As others have commented recently, we have a solution that has been in production for more than a year and this issue has just appeared without any changes on our side. Would be good to know we can safely implement the workaround mentioned above without causing any future problems?

**Comment by SDolha** [comment]
I think that with a server side solution, even with a client SDK that we can update to fix things (as it was not the case now), and even if it's Microsoft's responsibility, it can happen that backwards compatibility issues occur again and, more importantly, they could get unnoticed until too many end users find them and report them.

My suggestion is that we developers set up some periodic automatic testing calls on the APIs (e.g. use a dummy Planner Plan that we grant our agent access to) and let this service notify us in case of repeated unexpected results.

**Comment by amartinrelativity** [comment]
Upgrading from 3.23.0 -> 3.27.0 - fixed our null reference issues

**Comment by andrueastman** [comment]
Thanks for clarifying @amartinrelativity. Closing this as the Null Reference error is indeed resolved.

@SDolha @djswilly  
With regards to the having to set the ODataType to null, that is technically service/workload issue since the type property should not cause the error. We are however looking into working around this in the SDK and will resolve it once we comprehensively identify the workload types that don't like the ODataType being set. 
Related to https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/pull/312
