### ISSUE TITLE
Cannot deserialize change notification - System.InvalidCastException

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-sdk-dotnet#998]
**Describe the bug**
Attempting to deserialize the payload of a notification received by a [webhook](https://docs.microsoft.com/en-us/graph/webhooks) fails with a `System.InvalidCastException`.

**To Reproduce**
The following code will reproduce:

```
// This is an actual payload sent by the service that failed in my application
string payload = @"{
    ""value"": [
        {
            ""subscriptionId"": ""5c748643-b830-4b11-a165-cc4b59c9820c"",
            ""subscriptionExpirationDateTime"": ""2021-05-15T09:06:46.5737745-07:00"",
            ""changeType"": ""created"",
            ""resource"": ""Users/1023ccca-b008-40f6-950a-aa1951a1f0d4/Messages/AAMkADY0ZjM2ZWJlLTEwOGUtNGNiOS04MTFiLWE3Y2UwNjRiZDNiMQBGAAAAAACWRvY6Vjb0SabVPshsbtVRBwAtISQkTseOQLhQ9a0koD2UAAAAAAEMAAAtISQkTseOQLhQ9a0koD2UAAB9Mb9SAAA="",
            ""resourceData"": {
                ""@odata.type"": ""#Microsoft.Graph.Message"",
                ""@odata.id"": ""Users/1023ccca-b008-40f6-950a-aa1951a1f0d4/Messages/AAMkADY0ZjM2ZWJlLTEwOGUtNGNiOS04MTFiLWE3Y2UwNjRiZDNiMQBGAAAAAACWRvY6Vjb0SabVPshsbtVRBwAtISQkTseOQLhQ9a0koD2UAAAAAAEMAAAtISQkTseOQLhQ9a0koD2UAAB9Mb9SAAA="",
                ""@odata.etag"": ""W/\""CQAAABYAAAAtISQkTseOQLhQ9a0koD2UAAB9GwlV\"""",
                ""id"": ""AAMkADY0ZjM2ZWJlLTEwOGUtNGNiOS04MTFiLWE3Y2UwNjRiZDNiMQBGAAAAAACWRvY6Vjb0SabVPshsbtVRBwAtISQkTseOQLhQ9a0koD2UAAAAAAEMAAAtISQkTseOQLhQ9a0koD2UAAB9Mb9SAAA=""
            },
            ""clientState"": ""GraphTutorialState"",
            ""tenantId"": ""dfa81919-e5d3-4357-82ae-6b1e672fde09""
        }
    ]
}";

var jsonOptions = new JsonSerializerOptions
{
    PropertyNamingPolicy = JsonNamingPolicy.CamelCase
};

// Deserialize the JSON payload into a list of ChangeNotification
// objects
try
{
    var notifications = JsonSerializer.Deserialize<ChangeNotificationCollection>(payload, jsonOptions);
}
catch (Exception ex)
{
    Console.WriteLine(ex.ToString());
}
```

This gives:

```
System.InvalidCastException: Unable to cast object of type 'Microsoft.Graph.Message' to type 'Microsoft.Graph.ResourceData'.
   at Microsoft.Graph.DerivedTypeConverter`1.Read(Utf8JsonReader& reader, Type objectType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at Microsoft.Graph.DerivedTypeConverter`1.PopulateObject(Object target, JsonElement json, JsonSerializerOptions options)
   at Microsoft.Graph.DerivedTypeConverter`1.Read(Utf8JsonReader& reader, Type objectType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at Microsoft.Graph.DerivedTypeConverter`1.PopulateObject(Object target, JsonElement json, JsonSerializerOptions options)
   at Microsoft.Graph.DerivedTypeConverter`1.Read(Utf8JsonReader& reader, Type objectType, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

**Expected behavior**
The `notifications` variable contains a valid `ChangeNotificationCollection` object with one `ChangeNotification`.

**Client version**
4.0.0-preview.4

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**
Note that v3 gives a different exception (seems like enumeration deserialization isn't working here):

```
System.Text.Json.JsonException: The JSON value could not be converted to System.Nullable`1[Microsoft.Graph.ChangeType]. Path: $.value[0].changeType | LineNumber: 5 | BytePositionInLine: 35.
```

 
[AB#9468](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9468)

**Comment by andrueastman** [comment]
Thanks for raising this issue @jasonjoh. 

>Note that v3 gives a different exception (seems like enumeration deserialization isn't working here):

Just to clarify, by v3 do you mean preview.3 or version 3.x.x?

**Comment by jasonjoh** [comment]
Sorry - I mean version 3.x.x.

**Comment by andrueastman** [comment]
This fails in both v3 and v4 of the SDK since the type `#Microsoft.Graph.Message` does not derive or is not related to the [ResourceData](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/ffecbd4a279ee4292c9540c5468e39d90781bc8d/src/Microsoft.Graph/Generated/model/ResourceData.cs#L23) type.
This means that the property `resourceData` defined as type `ResourceData` cannot be assigned an object that is different from it. 

We will need to investigate this further and confirm if this is expected since I think it's unusual for the api to return a type that is unrelated to the type defined.

**Comment by andrueastman** [comment]
Related to https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/issues/107

**Comment by andrueastman** [comment]
This is resolved via microsoftgraph/msgraph-sdk-dotnet-core#256 and should now be available through https://www.nuget.org/packages/Microsoft.Graph/4.0.0-preview.6
